### ISSUE TITLE
crypto.com fetch_balance() produces ExchangeError

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#11179]
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: [1.66.39](https://github.com/ccxt/ccxt/tree/97b17c1e7ab7a58916286c4e268146a0caec70aa)

**Reproduction code**:
```
try {
	$id = "\\ccxt\\cryptocom";
	$exchange = new $id();
	$exchange->apiKey = "XXXX"; // let me know if you need temporary API key, I can make it for testing
	$exchange->secret = "YYYY";
	$exchange->enableRateLimit = true;

	$balance = $exchange->fetchBalance();
} catch (\ccxt\ExchangeError $e) {
	echo '[Exchange Error] ' . $e->getMessage();
	print_r($e);
}
```

**Error**:
```
[Exchange Error] cryptocom

ccxt\BadRequest Object
(
    [message:protected] => cryptocom 
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] =>  /path/to/composer/vendor/ccxt/ccxt/php/cryptocom.php
    [line:protected] => 1801
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1766
                    [function] => handle_errors
                    [class] => ccxt\cryptocom
                    [type] => ->
                )

            [1] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1522
                    [function] => fetch
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [2] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1526
                    [function] => fetch2
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [3] => Array
                (
                    [function] => request
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [4] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 2657
                    [function] => call_user_func_array
                )

            [5] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/cryptocom.php
                    [line] => 765
                    [function] => __call
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [6] => Array
                (
                    [file] => /path/to/my/script.php
                    [line] => 118
                    [function] => fetch_balance
                    [class] => ccxt\cryptocom
                    [type] => ->
                )

        )

    [previous:Exception:private] => 
)
```

**Comment by kroitor** [comment]
@c0dehunter thanks for reporting! Fixed in CCXT 1.66.64+.

**Comment by c0dehunter** [comment]
@kroitor thanks, but the issue persists even with 1.66.64. If it would help I can share temp API key for testing.

```
[Exchange Error] cryptocom

ccxt\BadRequest Object
(
    [message:protected] => cryptocom 
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] =>  /path/to/composer/vendor/ccxt/ccxt/php/cryptocom.php
    [line:protected] => 1815
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1766
                    [function] => handle_errors
                    [class] => ccxt\cryptocom
                    [type] => ->
                )

            [1] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1522
                    [function] => fetch
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [2] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 1526
                    [function] => fetch2
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [3] => Array
                (
                    [function] => request
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [4] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 2657
                    [function] => call_user_func_array
                )

            [5] => Array
                (
                    [file] =>  /path/to/composer/vendor/ccxt/ccxt/php/cryptocom.php
                    [line] => 765
                    [function] => __call
                    [class] => ccxt\Exchange
                    [type] => ->
                )

            [6] => Array
                (
                    [file] => /path/to/my/script.php
                    [line] => 118
                    [function] => fetch_balance
                    [class] => ccxt\cryptocom
                    [type] => ->
                )

        )

    [previous:Exception:private] => 
)
```

**Comment by c0dehunter** [comment]
I went ahead and tested the latest commit, and probably I'm too fast, but it seems `parseSpotBalance` was not added to Exchange class, causing:

`[Exchange Error] parseSpotBalance method not found, try underscore_notation instead of camelCase for the method being called`

**Comment by kroitor** [comment]
@c0dehunter you should also update the base files as well, make sure that your runtime CCXT version number in your script is 1.66.70+.

**Comment by c0dehunter** [comment]
I see, my manual script patching approach caused the above error. Updating CCXT to 1.66.70 fixed the issue and crypto.com is working well now. Thank you!
