### ISSUE TITLE
mexc function didn't works: createOrder()

### ISSUE THREAD

**Issue by franklee00** [ccxt/ccxt#11744]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu  20.04
- Programming Language version: javascript
- CCXT version: ^1.71.36

```
console.log( await mexc.createOrder('ETH_USDT','IMMEDIATE_OR_CANCEL','buy',200,0.99));
```

```
InvalidOrder: mexc createOrder() allows limit orders only
```

the code works well until today, but wrong now. Why is it? Is it because of the update of ccxt?

**Comment by kroitor** [comment]
@franklee00 it's a bug that was introduced upon upgrading the MEXC integration, i've pushed a fix for it, please, let me know if you have this issue or not with CCXT version 1.71.38+ (the new build will arrive in ~20 minutes). Thanks for your feedback!

**Comment by franklee00** [comment]
I reinstall ccxt with the version: 1.71.38
but a new error accured:

```
Error: 1e-4: invalid number (contains an illegal character 'e')
```

**Comment by kroitor** [comment]
@franklee00 i've pushed another fix in 1.71.39, tested on my side – it should work. However, with your values it will not work, cause you're trying to buy 200 ETH for a price of 0.99 USD per ETH. I think you have to switch 200 <> 0.99 in this case.

**Comment by franklee00** [comment]
switch 200 <> 0.99
I tried this, still not work.
the function works well for almost 2 month, therefore the params order should not be wrong.

**Comment by kroitor** [comment]
@franklee00 1.71.40 has not arrived yet, will arrive in ~5 minutes, it takes around twenty minutes to build a new version.

**Comment by franklee00** [comment]
Got it! thx a lot~

**Comment by franklee00** [comment]
It works, everything goes well again. thx @kroitor .
