### ISSUE TITLE
How to set market take profit?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#13831]
The code as follows:
```
import ccxt
import time
from pprint import pprint
ftx = ccxt.ftx({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})

symbol = 'BTC/USD:USD'
ftx.load_markets()
market = ftx.market(symbol)
btc_maket_price = float(market['info']['price'])
btc_amount = 20 / btc_maket_price
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)

type = 'takeProfit'
side = 'sell'
rise_btc_price = btc_maket_price + btc_maket_price * 0.015
params = {
    'stopPrice': rise_btc_price,
}
order = ftx.create_order(symbol, type, side, btc_amount, params)
```

The errors as follows:
Traceback (most recent call last):
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\contract.py", line 26, in <module>
    order = ftx.create_order(symbol, type, side, btc_amount, params)
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\ccxt\ftx.py", line 1625, in create_order
    raise InvalidOrder(self.id + ' createOrder() does not support order type ' + type + ', only limit, market, stop, trailingStop, or takeProfit orders are supported')
ccxt.base.errors.InvalidOrder: ftx createOrder() does not support order type takeProfit, only limit, market, stop, trailingStop, or takeProfit orders are supported

**Comment by frosty00** [comment]
please update to the latest version of ccxt, this issue should be fixed.

**Comment by qwe231cvb** [comment]
> please update to the latest version of ccxt, this issue should be fixed.

I have downloaded version 1.87.24 and still the problem persists.

**Comment by qwe231cvb** [comment]
Who anyone knows how to do?

**Comment by kroitor** [comment]
@qwe231cvb you have to upgrade to the most recent version of CCXT, but not only that, you also have to make sure that you have upgraded correctly by printing the actual CCXT version that you are using in runtime. Let us know if this does not work:

```Python
import ccxt
from pprint import pprint


print("CCXT Version:", ccxt.__version__)


ftx = ccxt.ftx({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary, after loading the markets

symbol = 'BTC/USD:USD'
ftx.load_markets()
market = ftx.market(symbol)
btc_maket_price = float(market['info']['price'])
btc_amount = 20 / btc_maket_price
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)

type = 'takeProfit'
side = 'sell'
rise_btc_price = btc_maket_price + btc_maket_price * 0.015
params = {
    'stopPrice': rise_btc_price,
}
order = ftx.create_order(symbol, type, side, btc_amount, params)
```

**Comment by qwe231cvb** [comment]
> @qwe231cvb you have to upgrade to the most recent version of CCXT, but not only that, you also have to make sure that you have upgraded correctly by printing the actual CCXT version that you are using in runtime.
> 
> Let us know if this does not work:
> 
> ```python
> import ccxt
> from pprint import pprint
> 
> 
> print("CCXT Version:", ccxt.__version__)
> 
> 
> ftx = ccxt.ftx({
>     'apiKey': 'my_apikey',
>     'secret': 'my_secret',
> })
> 
> markets = exchange.load_markets()
> 
> # exchange.verbose = True  # uncomment for debugging purposes if necessary, after loading the markets
> 
> symbol = 'BTC/USD:USD'
> ftx.load_markets()
> market = ftx.market(symbol)
> btc_maket_price = float(market['info']['price'])
> btc_amount = 20 / btc_maket_price
> create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
> 
> type = 'takeProfit'
> side = 'sell'
> rise_btc_price = btc_maket_price + btc_maket_price * 0.015
> params = {
>     'stopPrice': rise_btc_price,
> }
> order = ftx.create_order(symbol, type, side, btc_amount, params)
> ```

The problem persists, here is the printout:
CCXT Version: 1.87.24
Traceback (most recent call last):
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\contract.py", line 30, in <module>
    order = ftx.create_order(symbol, type, side, btc_amount, params)
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\ccxt\ftx.py", line 1625, in create_order
    raise InvalidOrder(self.id + ' createOrder() does not support order type ' + type + ', only limit, market, stop, trailingStop, or takeProfit orders are supported')
ccxt.base.errors.InvalidOrder: ftx createOrder() does not support order type takeProfit, only limit, market, stop, trailingStop, or takeProfit orders are supported

**Comment by kroitor** [comment]
@qwe231cvb you're making a market takeProfit order, so you have to specify price=None or the actual limit price:

```Python
import ccxt
from pprint import pprint


print("CCXT Version:", ccxt.__version__)


ftx = ccxt.ftx({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary, after loading the markets

symbol = 'BTC/USD:USD'
ftx.load_markets()
market = ftx.market(symbol)
btc_maket_price = float(market['info']['price'])
btc_amount = 20 / btc_maket_price
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)

type = 'takeProfit'
side = 'sell'
rise_btc_price = btc_maket_price + btc_maket_price * 0.015
params = {
    'stopPrice': rise_btc_price,
}
price = None  # or your takeProfit limit price  # -------- ↓
order = ftx.create_order(symbol, type, side, btc_amount, price, params)
```

Hope that answers your question.

**Comment by qwe231cvb** [comment]
> @qwe231cvb you're making a market takeProfit order, so you have to specify price=None or the actual limit price:
> 
> ```python
> import ccxt
> from pprint import pprint
> 
> 
> print("CCXT Version:", ccxt.__version__)
> 
> 
> ftx = ccxt.ftx({
>     'apiKey': 'my_apikey',
>     'secret': 'my_secret',
> })
> 
> markets = exchange.load_markets()
> 
> # exchange.verbose = True  # uncomment for debugging purposes if necessary, after loading the markets
> 
> symbol = 'BTC/USD:USD'
> ftx.load_markets()
> market = ftx.market(symbol)
> btc_maket_price = float(market['info']['price'])
> btc_amount = 20 / btc_maket_price
> create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
> 
> type = 'takeProfit'
> side = 'sell'
> rise_btc_price = btc_maket_price + btc_maket_price * 0.015
> params = {
>     'stopPrice': rise_btc_price,
> }
> price = None  # or your takeProfit limit price  # -------- ↓
> order = ftx.create_order(symbol, type, side, btc_amount, price, params)
> ```
> 
> Hope that answers your question.

It is ok now.
