### ISSUE TITLE
Gateio watch_order_book InvalidNonce error

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#16396]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

python

### CCXT Version

2.5.56

### Description

Hi guys,

With the latest version of ccxt, I cannot use "watch_order_book" on gate.
It returns:
`InvalidNonce: gateio orderbook update has a nonce bigger than u`

I found the error in the source code, but I've no idea on how to fix it.
Any way to bypass it, until it's fixed, maybe?

Btx, the `fetch_order_book` method works fine

Thanks for your great job :pray: 

### Code

```
from ccxt import pro as ccxtpro
exchange = ccxtpro.gateio()
i = 0
while i < 5:
    i += 1
    print(i)
    ob = await exchange.watch_order_book("DOGE/USDT", limit=20)
    print(ob)

```

**Comment by sc0Vu** [comment]
Hi @KevinBaudin

It worked for me, it seems the `nonce` (previous `u`) is smaller than `deltaStart - 1`. Would you like to add `verbose` and paste detail logs for websocket communication?

**Comment by frosty00** [comment]
@KevinBaudin it also works for me, if you want to increase the probability that it will work you can increase the delta cache:

```
gate.options['watchOrderBook']['snapshotDelay'] = 20
```

**Comment by KevinBaudin** [comment]
```
from ccxt import pro as ccxtpro
params = {'options': {
        "watchOrderBook": {'interval': '100ms', 'snapshotDelay': 20},
    }}
exchange = ccxtpro.gateio(params)
exchange.verbose = True
i = 0
while i < 5:
    i += 1
    print(i)
    ob = await exchange.watch_order_book("DOGE/USDT", limit=20)
```
Here is my current code. It does work properly only when I put verbose to True. Otherwise, it does an InvalidNonce.
I'll try to repeat and catch the error on verbose mode I guess...

**Comment by frosty00** [comment]
you can add a try, catch around await exchange.watchOrderBook and continue if it fails, it shouldn't fail very often due to not synching with the snapshot and should handle itself if it does

**Comment by KevinBaudin** [comment]
```
etch Request: gateio GET https://api.gateio.ws/api/v4/spot/order_book?currency_pair=DOGE_USDT&limit=20&with_id=true RequestHeaders: {'X-Gate-Channel-Id': 'ccxt', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None
2023-01-09T16:13:34.076Z message {"time":1673280813,"time_ms":1673280813940,"channel":"spot.order_book_update","event":"update","result":{"t":1673280813774,"e":"depthUpdate","E":1673280813,"s":"DOGE_USDT","U":4153443403,"u":4153443403,"b":[["0.078249","1000"],["0.077641","0"],["0.078228","127.86"],["0.077992","9778.57"]],"a":[]}}

fetch Response: gateio GET https://api.gateio.ws/api/v4/spot/order_book?currency_pair=DOGE_USDT&limit=20&with_id=true 200 ResponseHeaders: {'Date': 'Mon, 09 Jan 2023 16:13:34 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[4e0e2904-231992700]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} ResponseBody: {"id":4153443382,"current":1673280812880,"update":1673280812796,"asks":[["0.078302","4010.09"],["0.078328","1000"],["0.078329","4010.23"],["0.078362","1000"],["0.078363","2920.13"],["0.078364","7327.19"],["0.078384","1728.13"],["0.078394","40030"],["0.078395","310.93"],["0.078408","631.31"],["0.07841","344.43"],["0.078413","72.88"],["0.078415","2000"],["0.07843","105714.36"],["0.078442","70531.17"],["0.078444","330.14"],["0.078449","17.48"],["0.078457","157.1"],["0.078461","691.75"],["0.078469","202974.05"]],"bids":[["0.078301","1920.13"],["0.0783","1000"],["0.078288","1000"],["0.07828","6384.18"],["0.078276","1000"],["0.078268","1000"],["0.078256","1000"],["0.078252","1000"],["0.078248","8182.8"],["0.078244","10446.65"],["0.078243","40030"],["0.07824","6796.3"],["0.078239","1000"],["0.078235","1000"],["0.078233","1000"],["0.078231","1000"],["0.078229","1000"],["0.078226","9266.58"],["0.078224","387"],["0.078223","564.14"]]}
2023-01-09T16:13:34.343Z message {"time":1673280814,"time_ms":1673280814207,"channel":"spot.order_book_update","event":"update","result":{"t":1673280814068,"e":"depthUpdate","E":1673280814,"s":"DOGE_USDT","U":4153443404,"u":4153443404,"b":[["0.077644","0"],["0.078283","1000"],["0.078252","1000"],["0.078229","1000"],["0.077998","78.59"],["0.078285","1000"]],"a":[]}}

---------------------------------------------------------------------------
InvalidNonce                              Traceback (most recent call last)
Input In [1], in <cell line: 9>()
     10     i += 1
     11     print(i)
---> 12     ob = await asyncio.wait_for(
     13                     exchange.watch_order_book("DOGE/USDT", limit=20), timeout=120)
     14     print(ob)
     15 await exchange.close()

File ~/anaconda3/envs/anboto/lib/python3.8/asyncio/tasks.py:494, in wait_for(fut, timeout, loop)
    491         raise
    493 if fut.done():
--> 494     return fut.result()
    495 else:
    496     fut.remove_done_callback(cb)

File ~/anaconda3/envs/anboto/lib/python3.8/site-packages/ccxt/pro/gate.py:115, in gate.watch_order_book(self, symbol, limit, params)
    110     payload.append(stringLimit)
    111 subscription = {
    112     'symbol': symbol,
    113     'limit': limit,
    114 }
--> 115 orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
    116 return orderbook.limit()

File ~/anaconda3/envs/anboto/lib/python3.8/site-packages/ccxt/pro/gate.py:1015, in gate.subscribe_public(self, url, messageHash, payload, subscriptionHash, subscription, params)
   1010 subscription = self.extend(subscription, {
   1011     'id': requestId,
   1012     'messageHash': messageHash,
   1013 })
   1014 message = self.extend(request, params)
-> 1015 return await self.watch(url, messageHash, message, subscriptionHash, subscription)

InvalidNonce: gateio orderbook update has a nonce bigger than u

2023-01-09T16:13:34.828Z message {"time":1673280814,"time_ms":1673280814692,"channel":"spot.order_book_update","event":"update","result":{"t":1673280814516,"e":"depthUpdate","E":1673280814,"s":"DOGE_USDT","U":4153443405,"u":4153443405,"b":[["0.077644","9445.22"],["0.078228","0"]],"a":[]}}
```

Managed to catch this. But that's still very strange, I can't get any orderbook except when in verbose mode.
I'll try something else I guess

**Comment by frosty00** [comment]
@KevinBaudin i'll check the python behaviour

**Comment by frosty00** [comment]
please update to the latest build this error should be fixed

**Comment by KevinBaudin** [comment]
Thanks a lot

**Comment by leastchaos** [comment]
@frosty00 hi, could you check again? I still face this error after updating to version 2.6.13. once encounter, it cannot resolve. 
```
ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
ERROR:root:gateio orderbook update has a nonce bigger than u
Traceback (most recent call last):
  File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
    await exchange.watch_order_book("DOGE/USDT", limit=20)
  File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
    orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
  File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
    return await self.watch(url, messageHash, message, subscriptionHash, subscription)
ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
ERROR:root:gateio orderbook update has a nonce bigger than u
Traceback (most recent call last):
  File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
    await exchange.watch_order_book("DOGE/USDT", limit=20)
  File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
    orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
  File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
    return await self.watch(url, messageHash, message, subscriptionHash, subscription)
```

**Comment by carlosmiei** [comment]
> @frosty00 hi, could you check again? I still face this error after updating to version 2.6.13. once encounter, it cannot resolve.
> 
> ```
> import asyncio
> import logging
> from ccxt import pro as ccxtpro
> print(ccxtpro.__version__)
> exchange = ccxtpro.gateio()
> async def gateio_error():
>     await exchange.load_markets()
>     
>     while True:
>         try:
>             await exchange.watch_order_book("DOGE/USDT", limit=20)
>         except Exception as e:
>             logging.exception(e)
> 
> asyncio.run(gateio_error())
> ```
> 
> ```
> ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
> ERROR:root:gateio orderbook update has a nonce bigger than u
> Traceback (most recent call last):
>   File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
>     await exchange.watch_order_book("DOGE/USDT", limit=20)
>   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
>     orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
>   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
>     return await self.watch(url, messageHash, message, subscriptionHash, subscription)
> ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
> ERROR:root:gateio orderbook update has a nonce bigger than u
> Traceback (most recent call last):
>   File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
>     await exchange.watch_order_book("DOGE/USDT", limit=20)
>   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
>     orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
>   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
>     return await self.watch(url, messageHash, message, subscriptionHash, subscription)
> ```

Hello @leastchaos,
Do you mind updating to the latest version and trying again? I'm not able to reproduce this issue locally

**Comment by daqingsu19** [comment]
i have similar issue with watch_order_book().
tried all approaches above but still can't fix:
site-packages/ccxt/pro/gate.py", line 192, in handle_order_book
    cacheLength = len(storedOrderBook.cache)
AttributeError: 'NoneType' object has no attribute 'cache'

i use ccxt __version__ = '2.6.58'

fetch_order_book() has no problem.

**Comment by daqingsu19** [comment]
i set params as:
{
'interval': '50ms',
'snapshotDelay': 20,
},

**Comment by daqingsu19** [comment]
can someone help? appreciate it.

**Comment by daqingsu19** [comment]
> > @frosty00 hi, could you check again? I still face this error after updating to version 2.6.13. once encounter, it cannot resolve.
> > ```
> > import asyncio
> > import logging
> > from ccxt import pro as ccxtpro
> > print(ccxtpro.__version__)
> > exchange = ccxtpro.gateio()
> > async def gateio_error():
> >     await exchange.load_markets()
> >     
> >     while True:
> >         try:
> >             await exchange.watch_order_book("DOGE/USDT", limit=20)
> >         except Exception as e:
> >             logging.exception(e)
> > 
> > asyncio.run(gateio_error())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
> > ERROR:root:gateio orderbook update has a nonce bigger than u
> > Traceback (most recent call last):
> >   File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
> >     await exchange.watch_order_book("DOGE/USDT", limit=20)
> >   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
> >     orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
> >   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
> >     return await self.watch(url, messageHash, message, subscriptionHash, subscription)
> > ccxt.base.errors.InvalidNonce: gateio orderbook update has a nonce bigger than u
> > ERROR:root:gateio orderbook update has a nonce bigger than u
> > Traceback (most recent call last):
> >   File "/home/ubuntu/trading_bot/experiment/gateio_error.py", line 9, in gateio_error
> >     await exchange.watch_order_book("DOGE/USDT", limit=20)
> >   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 115, in watch_order_book
> >     orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)
> >   File "/home/ubuntu/miniconda/envs/trading_bot/lib/python3.10/site-packages/ccxt/pro/gate.py", line 1015, in subscribe_public
> >     return await self.watch(url, messageHash, message, subscriptionHash, subscription)
> > ```
> 
> Hello @leastchaos, Do you mind updating to the latest version and trying again? I'm not able to reproduce this issue locally
i have similar issue with watch_order_book().
tried all approaches above but still can't fix:
site-packages/ccxt/pro/gate.py", line 192, in handle_order_book
cacheLength = len(storedOrderBook.cache)
AttributeError: 'NoneType' object has no attribute 'cache'

i use ccxt version = '2.6.58'

fetch_order_book() has no problem.

i set params as:
{
'interval': '50ms',
'snapshotDelay': 20,
},

**Comment by lovepocky** [comment]
same error
```
  File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/gate.py", line 116, in watch_order_book
    orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)                                         
  File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/gate.py", line 990, in subscribe_public 
    return await self.watch(url, messageHash, message, messageHash, subscription)                                                            
ccxt.base.errors.InvalidNonce: gate orderbook update has a nonce bigger than u
```

and it maybe occurred when a new day coming.

## version
name = "ccxt"
version = "2.8.17"

**Comment by xalumok** [comment]
I've just caught the same exception, it appeared right when the clock struck 8 PM. 

> same error
> 
> ```
>   File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/gate.py", line 116, in watch_order_book
>     orderbook = await self.subscribe_public(url, messageHash, payload, channel, subscription, query)                                         
>   File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/gate.py", line 990, in subscribe_public 
>     return await self.watch(url, messageHash, message, messageHash, subscription)                                                            
> ccxt.base.errors.InvalidNonce: gate orderbook update has a nonce bigger than u
> ```
> 
> and it maybe occurred when a new hour coming.
> 
> ## version
> name = "ccxt" version = "2.8.17"

I've just caught the same exception, it appeared right when the clock struck 8 PM.

**Comment by ezequieljardim** [comment]
Hello everyone, how's it going? I've been having this issue with multiple versions, even with the latest one (`3.0.78`).
Also, I think it's not related to a new hour coming... it has happened 15:14, 15:31, today etc.

Any updates on this?
Thanks!

**Comment by Tongoko** [comment]
I have the same issue with 3.0.80

**Comment by Tongoko** [comment]
I just let it run longer and it seems that the error is happening every full hour

**Comment by vyahnov** [comment]
Same for me.

Ubuntu 18.04
Node 16.20

Datetime samples:
2023-06-24 11:59:59.657
2023-06-24 11:59:59.706
2023-06-24 21:00:00.208
2023-06-24 22:00:00.687
2023-06-25 00:59:54.082
2023-06-25 01:00:00.733
2023-06-25 02:00:00.125
2023-06-25 02:00:00.405
2023-06-25 02:00:00.594
2023-06-25 03:59:59.964
2023-06-25 04:00:00.766
2023-06-25 04:00:00.956

**Comment by mmletgo** [comment]
CCXT 4.1.45

I use exchange.verbose = True, so I find the detail.

The first message['u']=52478818263
The second message['U']=52478818264
So,it is OK.

The second message['u']=52478818287
The third message['U']=52478818813
So,it is not OK.

2023-11-10T07:27:28.119Z message {"time":1699601247,"time_ms":1699601247862,"channel":"futures.order_book_update","event":"update","result":{"U":52478818258,"a":[{"p":"36563","s":3935},{"p":"36564","s":1194}],"b":[{"p":"36541","s":546},{"p":"36537.2","s":0}],"s":"BTC_USDT","t":1699601247798,"u":52478818263}}

2023-11-10T07:27:28.245Z message {"time":1699601247,"time_ms":1699601247987,"channel":"futures.order_book_update","event":"update","result":{"U":52478818264,"a":[{"p":"36572.7","s":3316},{"p":"36561.4","s":0},{"p":"36567.8","s":3759},{"p":"36575.1","s":6711}],"b":[{"p":"36533.5","s":0},{"p":"36540.5","s":3211},{"p":"36537.2","s":27},{"p":"36557.1","s":1561},{"p":"36538","s":0},{"p":"36538.5","s":0},{"p":"36540.4","s":55},{"p":"36529.9","s":0},{"p":"36538.6","s":548},{"p":"36553.4","s":82},{"p":"36537","s":5187}],"s":"BTC_USDT","t":1699601247977,"u":52478818287}}

2023-11-10T07:27:28.374Z message {"time":1699601248,"time_ms":1699601248080,"channel":"futures.order_book_update","event":"update","result":{"U":52478818813,"a":[{"p":"36558.1","s":32970},{"p":"36570.2","s":994},{"p":"36567","s":5216},{"p":"36574.7","s":0},{"p":"36555.1","s":0},{"p":"36561.5","s":2099},{"p":"36557.1","s":90870},{"p":"36565.2","s":5875},{"p":"36554.9","s":10358},{"p":"36553.3","s":2295},{"p":"36574","s":0},{"p":"36553","s":0},{"p":"36564.7","s":4646},{"p":"36574.8","s":0},{"p":"36559.8","s":0},{"p":"36581.1","s":0},{"p":"36575.1","s":0},{"p":"36564","s":1094},{"p":"36569.1","s":11256},{"p":"36550.9","s":61727},{"p":"36566.1","s":2075},{"p":"36565.5","s":0},{"p":"36574.4","s":0},{"p":"36569","s":547},{"p":"36551.5","s":14076},{"p":"36560.7","s":0},{"p":"36563.3","s":3760},{"p":"36562.9","s":0},{"p":"36571.5","s":410},{"p":"36560.2","s":4549},{"p":"36560.1","s":360},{"p":"36572.7","s":3316},{"p":"36554.1","s":0},{"p":"36589","s":0},{"p":"36551.9","s":25572},{"p":"36557.2","s":62579},{"p":"36567.8","s":0},{"p":"36554.3","s":0},{"p":"36590.5","s":0},{"p":"36555","s":0},{"p":"36585.6","s":0},{"p":"36563.4","s":1369},{"p":"36558.2","s":726},{"p":"36560.4","s":1499},{"p":"36577.8","s":0},{"p":"36552","s":10904},{"p":"36575","s":0},{"p":"36574.1","s":0},{"p":"36571.2","s":11563},{"p":"36558.7","s":0},{"p":"36574.5","s":0},{"p":"36574.9","s":0},{"p":"36566.5","s":0},{"p":"36551.8","s":19000},{"p":"36559","s":765},{"p":"36568.3","s":12024},{"p":"36555.3","s":8416},{"p":"36552.7","s":0},{"p":"36551.4","s":48833},{"p":"36558.4","s":6011},{"p":"36573","s":0},{"p":"36572.6","s":547},{"p":"36570.4","s":14},{"p":"36556.6","s":2599},{"p":"36567.5","s":2280},{"p":"36558.3","s":17464},{"p":"36557","s":7171}],"b":[{"p":"36534.5","s":548},{"p":"36526.4","s":10243},{"p":"36539.9","s":5},{"p":"36547.7","s":0},{"p":"36540.9","s":429},{"p":"36535.6","s":54},{"p":"36544.9","s":3316},{"p":"36533","s":31822},{"p":"36547.4","s":0},{"p":"36552.9","s":0},{"p":"36529.4","s":681},{"p":"36542.7","s":0},{"p":"36539.7","s":16829},{"p":"36532.9","s":4},{"p":"36552.3","s":0},{"p":"36536.6","s":548},{"p":"36526.6","s":3297},{"p":"36548","s":800},{"p":"36546.3","s":0},{"p":"36527","s":143},{"p":"36542.3","s":0},{"p":"36540.6","s":0},{"p":"36549","s":0},{"p":"36538.8","s":143},{"p":"36532.7","s":5129},{"p":"36535.5","s":6497},{"p":"36515.6","s":0},{"p":"36544.3","s":13500},{"p":"36550.8","s":1100},{"p":"36546.5","s":10},{"p":"36526.8","s":1435},{"p":"36530.4","s":5712},{"p":"36526","s":28},{"p":"36534.2","s":5225},{"p":"36545.4","s":0},{"p":"36550.6","s":0},{"p":"36552.6","s":0},{"p":"36535","s":3955},{"p":"36527.9","s":3208},{"p":"36541.8","s":3345},{"p":"36534.9","s":1},{"p":"36557.1","s":0},{"p":"36526.5","s":5529},{"p":"36544.6","s":60},{"p":"36529","s":54},{"p":"36550.4","s":601},{"p":"36544.1","s":0},{"p":"36533.6","s":3206},{"p":"36531.2","s":26},{"p":"36530.7","s":8337},{"p":"36532","s":95},{"p":"36528.7","s":5130},{"p":"36554.9","s":0},{"p":"36554.5","s":0},{"p":"36554.2","s":0},{"p":"36541.5","s":1},{"p":"36534.6","s":3297},{"p":"36543.5","s":2017},{"p":"36535.1","s":4099},{"p":"36531.6","s":2952},{"p":"36537.1","s":3762},{"p":"36557","s":0},{"p":"36549.7","s":0},{"p":"36543","s":2785},{"p":"36534","s":548},{"p":"36541.9","s":385},{"p":"36543.2","s":0},{"p":"36529.3","s":3208},{"p":"36530.1","s":3317},{"p":"36550.5","s":176},{"p":"36546.6","s":0},{"p":"36536.5","s":5077},{"p":"36531.8","s":3216},{"p":"36540.8","s":0},{"p":"36541.4","s":0},{"p":"36535.2","s":1},{"p":"36534.4","s":35},{"p":"36533.8","s":2211},{"p":"36529.9","s":1},{"p":"36551.4","s":0},{"p":"36536.8","s":26},{"p":"36533.4","s":16},{"p":"36545.1","s":0},{"p":"36536.1","s":3426},{"p":"36546.8","s":3147},{"p":"36530","s":2481},{"p":"36541","s":0},{"p":"36553.5","s":0},{"p":"36548.2","s":0},{"p":"36545.5","s":0},{"p":"36551.8","s":0},{"p":"36533.9","s":736},{"p":"36550","s":40757},{"p":"36527.4","s":57},{"p":"36541.7","s":0},{"p":"36554.8","s":0},{"p":"36549.1","s":0},{"p":"36538.4","s":26},{"p":"36544.7","s":8282},{"p":"36554.4","s":0},{"p":"36556.9","s":0},{"p":"36548.8","s":0},{"p":"36538.6","s":0},{"p":"36551.9","s":0},{"p":"36542.9","s":0},{"p":"36535.9","s":4501},{"p":"36553.4","s":0},{"p":"36537.9","s":0},{"p":"36545.2","s":2446},{"p":"36531","s":1},{"p":"36542.5","s":0},{"p":"36547.8","s":0},{"p":"36539.5","s":0},{"p":"36546.7","s":7256},{"p":"36539","s":3164},{"p":"36525.2","s":0},{"p":"36555","s":0},{"p":"36540.2","s":0},{"p":"36533.3","s":13220},{"p":"36546","s":0},{"p":"36543.1","s":0},{"p":"36551.3","s":0},{"p":"36544.4","s":0},{"p":"36546.4","s":1096},{"p":"36545.3","s":0},{"p":"36539.6","s":0},{"p":"36526.2","s":5131},{"p":"36533.1","s":1},{"p":"36545","s":12604},{"p":"36523.9","s":0}],"s":"BTC_USDT","t":1699601248063,"u":52478818884}}

**Comment by mmletgo** [comment]
May it help to solve the problem to modify the ccxt.pro.gate.py
modify in handle_order_book()
`        elif nonce >= deltaEnd:
            return
        elif nonce >= deltaStart - 1:
            self.handle_delta(storedOrderBook, delta)
        else:
            # error = InvalidNonce(self.id + ' orderbook update has a nonce bigger than u')
            del client.subscriptions[messageHash]
            limit = self.safe_integer(subscription, 'limit')
            self.orderbooks[symbol] = self.order_book({}, limit)
            storedOrderBook = self.safe_value(self.orderbooks, symbol, self.order_book({}))
            cacheLength = 0
            snapshotDelay = self.handle_option('watchOrderBook', 'snapshotDelay', 10)
            waitAmount = snapshotDelay if isSpot else 0
            if cacheLength == waitAmount:
                # max limit is 100
                subscription = client.subscriptions[messageHash]
                limit = self.safe_integer(subscription, 'limit')
                self.spawn(self.load_order_book, client, messageHash, symbol, limit)
            storedOrderBook.cache.append(delta)
            return
            # del self.orderbooks[symbol]
            # client.reject(error, messageHash)
        client.resolve(storedOrderBook, messageHash)`

**Comment by imty42** [comment]
> CCXT 4.1.45
> 
> I use exchange.verbose = True, so I find the detail.
> 
> The first message['u']=52478818263 The second message['U']=52478818264 So,it is OK.
> 
> The second message['u']=52478818287 The third message['U']=52478818813 So,it is not OK.
> 
> 2023-11-10T07:27:28.119Z message {"time":1699601247,"time_ms":1699601247862,"channel":"futures.order_book_update","event":"update","result":{"U":52478818258,"a":[{"p":"36563","s":3935},{"p":"36564","s":1194}],"b":[{"p":"36541","s":546},{"p":"36537.2","s":0}],"s":"BTC_USDT","t":1699601247798,"u":52478818263}}
> 
> 2023-11-10T07:27:28.245Z message {"time":1699601247,"time_ms":1699601247987,"channel":"futures.order_book_update","event":"update","result":{"U":52478818264,"a":[{"p":"36572.7","s":3316},{"p":"36561.4","s":0},{"p":"36567.8","s":3759},{"p":"36575.1","s":6711}],"b":[{"p":"36533.5","s":0},{"p":"36540.5","s":3211},{"p":"36537.2","s":27},{"p":"36557.1","s":1561},{"p":"36538","s":0},{"p":"36538.5","s":0},{"p":"36540.4","s":55},{"p":"36529.9","s":0},{"p":"36538.6","s":548},{"p":"36553.4","s":82},{"p":"36537","s":5187}],"s":"BTC_USDT","t":1699601247977,"u":52478818287}}
> 
> 2023-11-10T07:27:28.374Z message {"time":1699601248,"time_ms":1699601248080,"channel":"futures.order_book_update","event":"update","result":{"U":52478818813,"a":[{"p":"36558.1","s":32970},{"p":"36570.2","s":994},{"p":"36567","s":5216},{"p":"36574.7","s":0},{"p":"36555.1","s":0},{"p":"36561.5","s":2099},{"p":"36557.1","s":90870},{"p":"36565.2","s":5875},{"p":"36554.9","s":10358},{"p":"36553.3","s":2295},{"p":"36574","s":0},{"p":"36553","s":0},{"p":"36564.7","s":4646},{"p":"36574.8","s":0},{"p":"36559.8","s":0},{"p":"36581.1","s":0},{"p":"36575.1","s":0},{"p":"36564","s":1094},{"p":"36569.1","s":11256},{"p":"36550.9","s":61727},{"p":"36566.1","s":2075},{"p":"36565.5","s":0},{"p":"36574.4","s":0},{"p":"36569","s":547},{"p":"36551.5","s":14076},{"p":"36560.7","s":0},{"p":"36563.3","s":3760},{"p":"36562.9","s":0},{"p":"36571.5","s":410},{"p":"36560.2","s":4549},{"p":"36560.1","s":360},{"p":"36572.7","s":3316},{"p":"36554.1","s":0},{"p":"36589","s":0},{"p":"36551.9","s":25572},{"p":"36557.2","s":62579},{"p":"36567.8","s":0},{"p":"36554.3","s":0},{"p":"36590.5","s":0},{"p":"36555","s":0},{"p":"36585.6","s":0},{"p":"36563.4","s":1369},{"p":"36558.2","s":726},{"p":"36560.4","s":1499},{"p":"36577.8","s":0},{"p":"36552","s":10904},{"p":"36575","s":0},{"p":"36574.1","s":0},{"p":"36571.2","s":11563},{"p":"36558.7","s":0},{"p":"36574.5","s":0},{"p":"36574.9","s":0},{"p":"36566.5","s":0},{"p":"36551.8","s":19000},{"p":"36559","s":765},{"p":"36568.3","s":12024},{"p":"36555.3","s":8416},{"p":"36552.7","s":0},{"p":"36551.4","s":48833},{"p":"36558.4","s":6011},{"p":"36573","s":0},{"p":"36572.6","s":547},{"p":"36570.4","s":14},{"p":"36556.6","s":2599},{"p":"36567.5","s":2280},{"p":"36558.3","s":17464},{"p":"36557","s":7171}],"b":[{"p":"36534.5","s":548},{"p":"36526.4","s":10243},{"p":"36539.9","s":5},{"p":"36547.7","s":0},{"p":"36540.9","s":429},{"p":"36535.6","s":54},{"p":"36544.9","s":3316},{"p":"36533","s":31822},{"p":"36547.4","s":0},{"p":"36552.9","s":0},{"p":"36529.4","s":681},{"p":"36542.7","s":0},{"p":"36539.7","s":16829},{"p":"36532.9","s":4},{"p":"36552.3","s":0},{"p":"36536.6","s":548},{"p":"36526.6","s":3297},{"p":"36548","s":800},{"p":"36546.3","s":0},{"p":"36527","s":143},{"p":"36542.3","s":0},{"p":"36540.6","s":0},{"p":"36549","s":0},{"p":"36538.8","s":143},{"p":"36532.7","s":5129},{"p":"36535.5","s":6497},{"p":"36515.6","s":0},{"p":"36544.3","s":13500},{"p":"36550.8","s":1100},{"p":"36546.5","s":10},{"p":"36526.8","s":1435},{"p":"36530.4","s":5712},{"p":"36526","s":28},{"p":"36534.2","s":5225},{"p":"36545.4","s":0},{"p":"36550.6","s":0},{"p":"36552.6","s":0},{"p":"36535","s":3955},{"p":"36527.9","s":3208},{"p":"36541.8","s":3345},{"p":"36534.9","s":1},{"p":"36557.1","s":0},{"p":"36526.5","s":5529},{"p":"36544.6","s":60},{"p":"36529","s":54},{"p":"36550.4","s":601},{"p":"36544.1","s":0},{"p":"36533.6","s":3206},{"p":"36531.2","s":26},{"p":"36530.7","s":8337},{"p":"36532","s":95},{"p":"36528.7","s":5130},{"p":"36554.9","s":0},{"p":"36554.5","s":0},{"p":"36554.2","s":0},{"p":"36541.5","s":1},{"p":"36534.6","s":3297},{"p":"36543.5","s":2017},{"p":"36535.1","s":4099},{"p":"36531.6","s":2952},{"p":"36537.1","s":3762},{"p":"36557","s":0},{"p":"36549.7","s":0},{"p":"36543","s":2785},{"p":"36534","s":548},{"p":"36541.9","s":385},{"p":"36543.2","s":0},{"p":"36529.3","s":3208},{"p":"36530.1","s":3317},{"p":"36550.5","s":176},{"p":"36546.6","s":0},{"p":"36536.5","s":5077},{"p":"36531.8","s":3216},{"p":"36540.8","s":0},{"p":"36541.4","s":0},{"p":"36535.2","s":1},{"p":"36534.4","s":35},{"p":"36533.8","s":2211},{"p":"36529.9","s":1},{"p":"36551.4","s":0},{"p":"36536.8","s":26},{"p":"36533.4","s":16},{"p":"36545.1","s":0},{"p":"36536.1","s":3426},{"p":"36546.8","s":3147},{"p":"36530","s":2481},{"p":"36541","s":0},{"p":"36553.5","s":0},{"p":"36548.2","s":0},{"p":"36545.5","s":0},{"p":"36551.8","s":0},{"p":"36533.9","s":736},{"p":"36550","s":40757},{"p":"36527.4","s":57},{"p":"36541.7","s":0},{"p":"36554.8","s":0},{"p":"36549.1","s":0},{"p":"36538.4","s":26},{"p":"36544.7","s":8282},{"p":"36554.4","s":0},{"p":"36556.9","s":0},{"p":"36548.8","s":0},{"p":"36538.6","s":0},{"p":"36551.9","s":0},{"p":"36542.9","s":0},{"p":"36535.9","s":4501},{"p":"36553.4","s":0},{"p":"36537.9","s":0},{"p":"36545.2","s":2446},{"p":"36531","s":1},{"p":"36542.5","s":0},{"p":"36547.8","s":0},{"p":"36539.5","s":0},{"p":"36546.7","s":7256},{"p":"36539","s":3164},{"p":"36525.2","s":0},{"p":"36555","s":0},{"p":"36540.2","s":0},{"p":"36533.3","s":13220},{"p":"36546","s":0},{"p":"36543.1","s":0},{"p":"36551.3","s":0},{"p":"36544.4","s":0},{"p":"36546.4","s":1096},{"p":"36545.3","s":0},{"p":"36539.6","s":0},{"p":"36526.2","s":5131},{"p":"36533.1","s":1},{"p":"36545","s":12604},{"p":"36523.9","s":0}],"s":"BTC_USDT","t":1699601248063,"u":52478818884}}


According to this, after the second msg '2023-11-10T07:27:28.245Z message' been handled,
`nonce = self.safe_integer(storedOrderBook, 'nonce')`
So, 
`nonce` = `52478818287`

And the third msg '2023-11-10T07:27:28.374Z message ', with `"U":52478818813, "u":52478818884` for short.
Which means `deltaStart`=`52478818813`, `deltaEnd`=`52478818884`.


The logic in `Python`, version `ccxt-4.2.79`
https://github.com/ccxt/ccxt/blob/e1d3914ed8b260627f30f88b92061ff0ceb38216/python/ccxt/pro/gate.py#L203

```
        nonce = self.safe_integer(storedOrderBook, 'nonce')
        if nonce is None:
            cacheLength = 0
            if storedOrderBook is not None:
                cacheLength = len(storedOrderBook.cache)
            snapshotDelay = self.handle_option('watchOrderBook', 'snapshotDelay', 10)
            waitAmount = snapshotDelay if isSpot else 0
            if cacheLength == waitAmount:
                # max limit is 100
                subscription = client.subscriptions[messageHash]
                limit = self.safe_integer(subscription, 'limit')
                self.spawn(self.load_order_book, client, messageHash, symbol, limit, {})  # needed for c#, number of args needs to match
            storedOrderBook.cache.append(delta)
            return
        elif nonce >= deltaEnd:
            return
        elif nonce >= deltaStart - 1:
            self.handle_delta(storedOrderBook, delta)
        else:
-->         error = InvalidNonce(self.id + ' orderbook update has a nonce bigger than u')
            del client.subscriptions[messageHash]
            del self.orderbooks[symbol]
            client.reject(error, messageHash)
```


@sc0Vu @carlosmiei please check this

**Comment by kroitor** [comment]
Hello @KevinBaudin, closing this long running thread during a cleanup — the failure mode everyone here hit was redesigned away: the gate orderbook stream now runs a proper nonce state machine, stale deltas are dropped, contiguous deltas are applied, and a sequence gap tears down the subscription and the book and resyncs from a fresh snapshot, optionally surfacing a structured ChecksumError instead of the raw InvalidNonce that this thread collected, with a snapshotDelay option controlling initial snapshot timing, and the snapshot fetch path itself was hardened further very recently. If a gate book still desyncs on a current version, a fresh issue with a verbose log would be very welcome. Thanks to everyone for the diagnostics gathered here over the years!
