### ISSUE TITLE
CoinEx Websocket watch_orders()

### ISSUE THREAD

**Issue by MikaelLind** [ccxt/ccxt#17190]
### Programming Languages

python

### CCXT Version

2.7.23

### Description

When trying to use the CCXT pro websocket function watch_orders for CoinEx I get this error:
```
TypeError: a coroutine was expected, got <Future pending>
```

The same code works fine for other exchanges.

Code I'm executing:
```
orders = await ccxt.watch_orders()
```

**Comment by carlosmiei** [comment]
Hello @MikaelLind,
That issue should be fixed already, can you try to update your ccxt versions?

**Comment by MikaelLind** [comment]
@carlosmiei - do you know in which version this is resolved in?

**Comment by carlosmiei** [comment]
> @carlosmiei - do you know in which version this is resolved in?

@MikaelLind Yes, it should be fixed in any version >= 2.9.4

**Comment by MikaelLind** [comment]
@carlosmiei I still have the same problem after updating to the lastest version of ccxt

**Comment by wenrenyueke** [comment]
I still have the same problem after updating to 3.0.35 version of ccxt,

**Comment by wenrenyueke** [comment]
I still have the same problem after updating to 3.0.35 version of ccxt,
with 3.11.2 version of python

**Comment by jonatw** [comment]
I got the same issue with 3.0.69 version

when I try to my own order status using watch_orders function

```
    coinex = ccxt.pro.coinex({
        'apiKey': api_secret['coinex]['access_key'],
        'secret': api_secret['coinex]['secret_key'],
        'enableRateLimit':True,
        'options': {
            'defaultType': 'swap'
        }
    })
```


it works okay with public api such as 

```
await coinex.load_fees()
await coinex.load_markets()
```


but when I call the private api, the error shows up

```
order = await coinex.watch_orders()
print(order)
```

error message

```
/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py:71: RuntimeWarning: coroutine 'ClientSession._ws_connect' was never awaited
  _cancel_all_tasks(loop)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/Users/user/proj/farb/websocket.py", line 46, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/user/proj/farb/websocket.py", line 36, in main
    order = await coinex.watch_orders()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/pro/coinex.py", line 589, in watch_orders
    await self.authenticate(params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/pro/coinex.py", line 969, in authenticate
    self.spawn(self.watch, url, messageHash, request, requestId, subscribe)
  File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 280, in spawn
    task = self.asyncio_loop.create_task(method(*args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got <Future pending>
```

**Comment by grozz97** [comment]
> I got the same issue with 3.0.69 version
> 
> when I try to my own order status using watch_orders function
> 
> ```
>     coinex = ccxt.pro.coinex({
>         'apiKey': api_secret['coinex']['access_key'],
>         'secret': api_secret['coinex']['secret_key'],
>         'enableRateLimit':True,
>         'options': {
>             'defaultType': 'swap'
>         }
>     })
> ```
> 
> it works okay with public api such as
> 
> ```
> await coinex.load_fees()
> await coinex.load_markets()
> ```
> 
> but when I call the private api, the error shows up
> 
> ```
> order = await coinex.watch_orders()
> print(order)
> ```
> 
> error message
> 
> ```
> /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py:71: RuntimeWarning: coroutine 'ClientSession._ws_connect' was never awaited
>   _cancel_all_tasks(loop)
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> Traceback (most recent call last):
>   File "/Users/user/proj/farb/websocket.py", line 46, in <module>
>     asyncio.run(main())
>   File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/Users/user/proj/farb/websocket.py", line 36, in main
>     order = await coinex.watch_orders()
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/pro/coinex.py", line 589, in watch_orders
>     await self.authenticate(params)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/pro/coinex.py", line 969, in authenticate
>     self.spawn(self.watch, url, messageHash, request, requestId, subscribe)
>   File "/Users/user/proj/farb/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 280, in spawn
>     task = self.asyncio_loop.create_task(method(*args))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 436, in create_task
>     task = tasks.Task(coro, loop=self, name=name, context=context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: a coroutine was expected, got <Future pending>
> coinex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x1006142d0>
> Unclosed connector
> connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1035eaeb0>, 149515.667764791), (<aiohttp.client_proto.ResponseHandler object at 0x1035eb380>, 149516.244738333)]']
> connector: <aiohttp.connector.TCPConnector object at 0x100604090>
> ```

I have the same problem in version **3.1.3**.

**Comment by carlosmiei** [comment]
@MikaelLind @wenrenyueke @jonatw @grozz97 I'm sorry, it seems the problem persists, I'm checking it now

**Comment by carlosmiei** [comment]
@MikaelLind @wenrenyueke @jonatw @grozz97 
It should be fixed by now, as of 3.1.5

Thanks

**Comment by grozz97** [comment]
@carlosmiei Thanks
