### ISSUE TITLE
Deribit fetch_ticker return error

### ISSUE THREAD

**Issue by Tropmathise** [ccxt/ccxt#17656]
### Programming Languages

python

### CCXT Version

last

### Description

Error in deribit.load_markets() returning error for different function such as fect_tickers and all function using load_markets

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Tropmathise, thanks for letting us know, we already merged a fix and a new release should be out in a few minutes.

**Comment by Tropmathise** [comment]
I think fetch_tickers doesnt work for code USDC

**Comment by RomainRouphael** [comment]
Any update on this please? Still doesn't work for with the latest version. Thank you

**Comment by carlosmiei** [comment]
> Any update on this please? Still doesn't work for with the latest version. Thank you

@RomainRouphael Which symbol are you using?

**Comment by tondy1** [comment]
Working for me again on revision 76. Thx!

**Comment by RomainRouphael** [comment]
> > Any update on this please? Still doesn't work for with the latest version. Thank you
> 
> @RomainRouphael Which symbol are you using?

I'm just calling deribit.fetchBalance(), used to work properly..
deribit.fetch_ticker('BTC-PERPETUAL') doesn't work either.

I updated to that latest version of the python package

**Comment by carlosmiei** [comment]
> BTC-PERPETUA

@RomainRouphael I just tested and seems to be working:
```
✗ p deribit fetchTicker "BTC-PERPETUAL"
Python v3.10.9
CCXT v3.0.76
deribit.fetchTicker(BTC-PERPETUAL)
{'ask': 27443.0,
 'askVolume': 12620.0,
 'average': None,
 'baseVolume': None,
 'bid': 27442.5,
 'bidVolume': 7310.0,
 'change': None,
 'close': 27448.5,
 'datetime': '2023-04-25T13:32:53.968Z',
 'high': 27715.0,
 'info': {'best_ask_amount': '12620.0',
          'best_ask_price': '27443.0',
          'best_bid_amount': '7310.0',
          'best_bid_price': '27442.5',
          'current_funding': '0.0',
          'estimated_delivery_price': '27447.53',
          'funding_8h': '0.0',
          'index_price': '27447.53',
          'instrument_name': 'BTC-PERPETUAL',
          'interest_value': '0.0',
          'last_price': '27448.5',
          'mark_price': '27442.52',
          'max_price': '27855.07',
          'min_price': '27031.77',
          'open_interest': '463892540',
          'settlement_price': '27265.84',
          'state': 'open',
          'stats': {'high': '27715.0',
                    'low': '26955.0',
                    'price_change': '0.2154',
                    'volume': '7756.76101356',
                    'volume_notional': '212120440.0',
                    'volume_usd': '212120440.0'},
          'timestamp': '1682429573968'},
 'last': 27448.5,
 'low': 26955.0,
 'open': None,
```
Can you double check your ccxt version? you can add this to your code: `print('CCXT Version:', ccxt.__version__)`

**Comment by Tropmathise** [comment]
deribit.fetch_tickers() doesnot work for me. Version 3.0.76

**Comment by carlosmiei** [comment]
> deribit.fetch_tickers() doesnot work for me. Version 3.0.76

@Tropmathise same error? As suggested did you check your ccxt version by adding `print('CCXT Version:', ccxt.__version__)` to the code?

**Comment by carlosmiei** [comment]
> @carlosmiei Yes it says argument required print('CCXT Version:', ccxt.**version**) deribit.fetch_tickers()
> 
> ## CCXT Version: 3.0.78
> ArgumentsRequired: deribit safeMarket() requires a fourth argument for BTC_USDC to disambiguate between different markets with the same market id

@Tropmathise that is indeed a different issue, will take a look asap.

**Comment by Tropmathise** [comment]
Thanks, please keep me updated when fixed on python
