### ISSUE TITLE
ccxt Binance "code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"

### ISSUE THREAD

**Issue by hvagday** [ccxt/ccxt#18853]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.0.56

### Description

I'm trading Binance Futures

Since a few days ago, I got error message "code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"

When I looked up github and stackoverflow, I saw a case that was solved by updating the ccxt version, but I couldn't solve the problem with that method. (my current ccxt version: 4.0.56)

Also, there is no direct use of v1 endpoint in my code.
So I doubt there's any part of ccxt that still uses v1 endpoint.

Please review it.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hvagday 

Would you like to paster verbose log for fetchPositions (verbose: true)?

**Comment by hvagday** [comment]
Traceback (most recent call last):
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1691725501883&symbol=XRPUSDT&signature=8adaae2cfe24babe5f2751be344deeec03a474b93b5e8ae5e168ce38f150ab15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sty1849/rtt/rtt_200_xrp.py", line 278, in <module>
    mode = u_isolated_type(exchange, symbol, "cross")
  File "/home/sty1849/rtt/rtt_200_xrp.py", line 46, in u_isolated_type
    res = self.fapiPrivateGetPositionRisk({"symbol": symbol2})[0]["marginType"]
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/binance.py", line 7480, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 616, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/sty1849/.local/lib/python3.10/site-packages/ccxt/binance.py", line 7458, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}

---

Is this enough for you? or need more verbose log?

**Comment by sc0Vu** [comment]
That's weird, I can't reproduce the issue. That would be great if you can paste the function you call and exchange version (__version__).

**Comment by carlosmiei** [comment]
Hello @hvagday, can you please double-check your ccxt version by printing (`print(ccxt.__version__)`), sometimes there is a discrepancy between the global version and the environment one

**Comment by kroitor** [comment]
@hvagday please, post your runtime version number, run this code:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

You should have version 4.0.57 or later.

**Comment by hvagday** [comment]
@sc0Vu @carlosmiei @kroitor Thank you for answer.
I just updated the version to 4.0.57, and I'm running the program.
I will leave a comment again on whether the issue is resolved or not.

**Comment by hvagday** [comment]
Now my ccxt version is 4.0.57, but still occurs.
---
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 4.0.57
---

**Comment by hvagday** [comment]
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 4.0.57

**Comment by kroitor** [comment]
@hvagday as you've closed this issue – is it resolved now? Can you elaborate a bit on what was the cause and how you fixed it?

**Comment by hvagday** [comment]
@kroitor Sorry, my mistake. It's not reseolved.

**Comment by kroitor** [comment]
@hvagday please, post the code to reproduce it, including the exchange instantiation but without your keys.

**Comment by hvagday** [comment]
@kroitor In ccxt version 4.0.60, I ran code below

```
import test_p
import ccxt

print("CCXT Version:", ccxt.__version__)
exchange = ccxt.binance(
    {
        "apiKey": 'MY_API_KEY',
        "secret": 'MY_API_SECRET',
    }
)
markets = exchange.load_markets()
exchange.verbose = True
# response = exchange.fetch_positions("XRP/USDT:USDT")
response2 = exchange.fapiPrivateGetPositionRisk({"symbol": "XRPUSDT"})
```

And the result is as follows.
---
CCXT Version: 4.0.60

fetch Request: binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1692064723259&symbol=XRPUSDT&recvWindow=10000&signature=17d4cc62348456a9c14ebeeeacba1514e9966e0ddb5845a30439232c05aed5b1 RequestHeaders: {'X-MBX-APIKEY': 'MY_API_KEY', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1692064723259&symbol=XRPUSDT&recvWindow=10000&signature=17d4cc62348456a9c14ebeeeacba1514e9966e0ddb5845a30439232c05aed5b1 200 ResponseHeaders: {'Date': 'Tue, 15 Aug 2023 01:58:43 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '4', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip'} ResponseBody: [{"symbol":"XRPUSDT","positionAmt":"0.0","entryPrice":"0.0","markPrice":"0.62990000","unRealizedProfit":"0.00000000","liquidationPrice":"0","leverage":"2","maxNotionalValue":"30000000","marginType":"isolated","isolatedMargin":"0.00000000","isAutoAddMargin":"false","positionSide":"BOTH","notional":"0","isolatedWallet":"0","updateTime":1637740806705}]
---

Looking at the results, I think I can see the part that uses "v1".

**Comment by hvagday** [comment]
I accidentally pressed the close issue button again. I'm sorry.

**Comment by Samuel1043** [comment]
for me exchange.fapiPrivateGetPositionRisk sometimes work but sometimes don't 
<img width="512" alt="image" src="https://github.com/ccxt/ccxt/assets/44538574/794cf95e-7d6e-4498-839c-7bef8879ce84">

change `exchange.fapiPrivateGetPositionRisk` to `exchange.fapiPrivateV2GetPositionRisk` may work

**Comment by hvagday** [comment]
@Samuel1043 It works well. Thank you!!!

**Comment by layalihamam** [comment]
Hey, Having the same issue but can't find the v1 that is causing the problem is there anyway you can help me with that ?

**Comment by Samuel1043** [comment]
As i commented above from binance-um api doc V1 no longer supported from 2023/7/15, can switch to V2

**Comment by layalihamam** [comment]
@Samuel1043 Yes i saw but i dont have any of thesse V1 un my code 
i don't see any 
exchange.fapiPrivateGetPositionRisk
or : GET /fapi/v1/positionRisk

**Comment by layalihamam** [comment]
`Exception in thread Thread-1 (f1):

Traceback (most recent call last):

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner

    [self.run](https://self.run/)()

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run

    self._target(*self._args, **self._kwargs)

  File "C:\Users\pro\Downloads\try888\main.py", line 8, in f1

    [bot1.run](https://bot1.run/)()

  File "C:\Users\pro\Downloads\try888\classes.py", line 174, in run

    x = client.futures_position_information(symbol=self.symbol)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 6327, in futures_position_information

    return self._request_futures_api('get', 'positionRisk', True, data=params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 382, in _request_futures_api

    return self._request(method, uri, signed, True, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 358, in _request

    return self._handle_response(self.response)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\binance\client.py", line 367, in _handle_response

    raise BinanceAPIException(response, response.status_code, response.text)

binance.exceptions.BinanceAPIException: APIError(code=-5000): GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk`

as you see this is my error

**Comment by Samuel1043** [comment]
Are you sure you are using ccxt, from your path i think you were using site-packages `binance`

**Comment by layalihamam** [comment]
yes we are using binance - binance.client

**Comment by carlosmiei** [comment]
> yes we are using binance - binance.client

@layalihamam  In that case this is not the suitable repository for you.

**Comment by layalihamam** [comment]
oh okay thank you

**Comment by chan1919** [comment]
> for me exchange.fapiPrivateGetPositionRisk sometimes work but sometimes don't below is the screenshot from binance api doc V1 no longer supported from 2023/7/15 <img alt="image" width="512" src="https://user-images.githubusercontent.com/44538574/260682855-794cf95e-7d6e-4498-839c-7bef8879ce84.png">
> 
> change `exchange.fapiPrivateGetPositionRisk` to `exchange.fapiPrivateV2GetPositionRisk` may work

oh，how to change?

**Comment by carlosmiei** [comment]
> > for me exchange.fapiPrivateGetPositionRisk sometimes work but sometimes don't below is the screenshot from binance api doc V1 no longer supported from 2023/7/15 <img alt="image" width="512" src="https://user-images.githubusercontent.com/44538574/260682855-794cf95e-7d6e-4498-839c-7bef8879ce84.png">
> > change `exchange.fapiPrivateGetPositionRisk` to `exchange.fapiPrivateV2GetPositionRisk` may work
> 
> oh，how to change?

@chan1919 If you update your ccxt version the issue should be fixed

**Comment by Cortii2** [comment]
Hi! I'm on the latest v4.1.74 and still getting this annoying issue regarding to v1 is deprecated... :o 

`binance {\"code\":-5000,\"msg\":\"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk\"}`

**Comment by sirpy** [comment]
this still happens

**Comment by carlosmiei** [comment]
@sirpy What's your ccxt version? Please make sure you have an updated version of ccxt

**Comment by sirpy** [comment]
@carlosmiei i have the latest one. which version was it fixed at?

**Comment by carlosmiei** [comment]
@sirpy This was fixed a long time ago, so it seems you're not running an updated version
