### ISSUE TITLE
kucoinfutures not properly handling temporary errors (token expired)

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#18872]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.0.40

### Description

Hi,

Contrary to other exchanges I have tested kucoinfutures never seems to recover from temporary failures. 

Here's my code:

### Code

```
import ccxt.pro as ccxt
import asyncio

kucoin = ccxt.kucoinfutures({"verbose": True})


async def watch_symbol(symbol):
    while True:
        try:
            await kucoin.watch_trades(symbol=symbol)
        except Exception as error:
            print(error)

asyncio.run(watch_symbol("AVAX/USDT:USDT"))
```

Logs:

```
2023-08-13T06:07:39.939Z connecting to wss://ws-api-futures.kucoin.com/?token=2neAiuYvAU61ZDXANAGAsiL4-iAExhsBXZxftpOeh_55i3Ysy2q2LEsEWU64mdzUOPusi34M_wGoSf7iNyEWJ6W0n0-gKeQYbtSgBapA1pWD_gEvD1kNxNiYB9J6i9GjsxUuhPw3BlrzazF6ghq4L0aX6AdmNViFvl6LR_U08_0%3D.jKAinlr5f4HNZ52lqEQNpA%3D%3D&privateChannel=false&connectId=public with timeout 10000 ms
2023-08-13T06:07:41.005Z connected
2023-08-13T06:07:41.005Z ping loop
2023-08-13T06:07:41.005Z sending {'id': '484157', 'type': 'ping'}
2023-08-13T06:07:41.006Z sending {'id': '484120', 'type': 'subscribe', 'topic': '/contractMarket/execution:AVAXUSDTM', 'response': True}
2023-08-13T06:07:41.008Z message {"id":"64d8732c856851144bded10d","type":"error","code":401,"data":"token is expired"}
2023-08-13T06:07:41.008Z close False WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='Bye')
2023-08-13T06:07:41.008Z on_close 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
2023-08-13T06:07:41.009Z closing 1000
2023-08-13T06:07:41.009Z connecting to wss://ws-api-futures.kucoin.com/?token=2neAiuYvAU61ZDXANAGAsiL4-iAExhsBXZxftpOeh_55i3Ysy2q2LEsEWU64mdzUOPusi34M_wGoSf7iNyEWJ6W0n0-gKeQYbtSgBapA1pWD_gEvD1kNxNiYB9J6i9GjsxUuhPw3BlrzazF6ghq4L0aX6AdmNViFvl6LR_U08_0%3D.jKAinlr5f4HNZ52lqEQNpA%3D%3D&privateChannel=false&connectId=public with timeout 10000 ms
2023-08-13T06:07:41.009Z on_error 1006
2023-08-13T06:07:41.645Z connected
2023-08-13T06:07:41.645Z ping loop
2023-08-13T06:07:41.645Z sending {'id': '484195', 'type': 'ping'}
2023-08-13T06:07:41.645Z sending {'id': '484158', 'type': 'subscribe', 'topic': '/contractMarket/execution:AVAXUSDTM', 'response': True}
2023-08-13T06:07:41.651Z message {"id":"64d8732d856851144bded11f","type":"error","code":401,"data":"token is expired"}
2023-08-13T06:07:41.652Z close False WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='Bye')
2023-08-13T06:07:41.652Z on_close 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
Connection closed by remote server, closing code 1000
2023-08-13T06:07:41.009Z closing 1000
2023-08-13T06:07:41.009Z connecting to wss://ws-api-futures.kucoin.com/?token=2neAiuYvAU61ZDXANAGAsiL4-iAExhsBXZxftpOeh_55i3Ysy2q2LEsEWU64mdzUOPusi34M_wGoSf7iNyEWJ6W0n0-gKeQYbtSgBapA1pWD_gEvD1kNxNiYB9J6i9GjsxUuhPw3BlrzazF6ghq4L0aX6AdmNViFvl6LR_U08_0%3D.jKAinlr5f4HNZ52lqEQNpA%3D%3D&privateChannel=false&connectId=public with timeout 10000 ms
2023-08-13T06:07:41.009Z on_error 1006
2023-08-13T06:07:41.645Z connected
2023-08-13T06:07:41.645Z ping loop
2023-08-13T06:07:41.645Z sending {'id': '484195', 'type': 'ping'}
2023-08-13T06:07:41.645Z sending {'id': '484158', 'type': 'subscribe', 'topic': '/contractMarket/execution:AVAXUSDTM', 'response': True}
2023-08-13T06:07:41.651Z message {"id":"64d8732d856851144bded11f","type":"error","code":401,"data":"token is expired"}
2023-08-13T06:07:41.652Z close False WSMessage(type=<WSMsgType.CLOSE: 8>, data=1000, extra='Bye')
2023-08-13T06:07:41.652Z on_close 1000

 

```

This goes on like this for quite some time. And later:

```
Cannot write to closing transport
Cannot write to closing transport
Cannot write to closing transport
```

**Comment by carlosmiei** [comment]
Hello @mrpouley, thanks for letting us know we will take a look

**Comment by pcriadoperez** [comment]
Hi @mrpouley , I wasn't able to reproduce the exact error but I believe PR #18889 should fix the issue

**Comment by mrpouley** [comment]
Thanks i'll let you know.

**Comment by mrpouley** [comment]
Hello,

Unfortunately the problem is still there with version 4.1.18. Both kucoin and kucoinfutures exchange classes are impacted (other exchanges are fine).

I have hard time reproducing it locally since it happens so rarely. On my production server though the issue arises every three or four days, forcing me to restart the program.
