### ISSUE TITLE
New Bitget newSize field for websocket orders

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#21181]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Following the conversation here:
https://github.com/ccxt/ccxt/issues/20868

I'm afraid since it's closed it won't be checked.
I was having major issues on orders statuses concerning filled/amount/remaining

### Describe the solution you'd like

Bitget did update their api so CCXT could use it for a better tracking of orders state

 https://www.bitget.com/api-doc/common/changelog
See the newSize part

**Comment by sc0Vu** [comment]
Hi @KevinBaudin 

I've checked the updates and the partial filled example in this comment: https://github.com/ccxt/ccxt/issues/20868#issuecomment-1914190470, may I ask what's the filled amount and the remaining should be?

**Comment by KevinBaudin** [comment]
In this example with partially filled, the `filled` was 200 for a cost of 15.7. It should have been `200/ 15.7 = 12.73...` because they are using quote coin instead of base coin.
remaining should be `amount - filled`

**Comment by KevinBaudin** [comment]
Any update on this please? just so I can have a rough estimation on when you plan to use it approx

**Comment by KevinBaudin** [comment]
Please :) ? How can I help on this also?

**Comment by carlosmiei** [comment]
@KevinBaudin Sorry for the delay, we're going to take a look

**Comment by sc0Vu** [comment]
Hi @KevinBaudin,

I wonder about this:
Since the size represents quote size for buy (usdt), is the filled number is `cost / price` => `15.7 / 0.78257 = 20.06210307065183`, am I correct?

**Comment by KevinBaudin** [comment]
it works as an approximation yes

**Comment by KevinBaudin** [comment]
the PR looks good to me, I'm impatient to test it so I can be over with this issue :D

**Comment by carlosmiei** [comment]
@KevinBaudin I tweaked a bit to fix other issues (amount missing in some cases, etc), and we will merge it shortly.

**Comment by KevinBaudin** [comment]
Any updates ? :pray: Thanks a lot again

**Comment by carlosmiei** [comment]
Hello @KevinBaudin, I merged the pR last week. Have you had the chance to update and try again?

**Comment by KevinBaudin** [comment]
Hi
I just tested it, and there is still some issues sadly
version: 4.2.58

```
{'info': {'instId': 'DOGEUSDT', 'orderId': '1148566467643871233', 'clientOid': '7170437438236528640', 'price': '0.167961', 'size': '25.1941', 'newSize': '150.0000', 'notional': '25.194150', 'orderType': 'limit', 'force': 'gtc', 'side': 'buy', 'accBaseVolume': '150.0000', 'priceAvg': '0.167942', 'status': 'filled', 'cTime': '1709565505896', 'uTime': '1709565506061', 'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.15'}], 'enterPointSource': 'API'}, 'symbol': 'DOGE/USDT', 'id': '1148566467643871233', 'clientOrderId': '7170437438236528640', 'timestamp': 1709565505896, 'datetime': '2024-03-04{'info': {'instId': 'DOGEUSDT',
  'orderId': '1148566467643871233',
  'clientOid': '7170437438236528640',
  'price': '0.167961',
  'size': '25.1941',
  'newSize': '150.0000',
  'notional': '25.194150',
  'orderType': 'limit',
  'force': 'gtc',
  'side': 'buy',
  'accBaseVolume': '150.0000',
  'priceAvg': '0.167942',
  'status': 'filled',
  'cTime': '1709565505896',
  'uTime': '1709565506061',
  'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.15'}],
  'enterPointSource': 'API'},
 'symbol': 'DOGE/USDT',
 'id': '1148566467643871233',
 'clientOrderId': '7170437438236528640',
 'timestamp': 1709565505896,
 'datetime': '2024-03-04T15:18:25.896Z',
 'lastTradeTimestamp': 1709565506061,
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'side': 'buy',
 'price': 0.167961,
 'stopPrice': None,
 'triggerPrice': None,
 'amount': 25.1941,
 'cost': 25.19415,
 'average': 0.167942,
 'filled': 150.0,
 'remaining': -124.8059,
 'status': 'closed',
 'fee': {'cost': '0.15', 'currency': 'DOGE'},
 'trades': [],
 'fees': [{'cost': 0.15, 'currency': 'DOGE'}],
 'lastUpdateTimestamp': None,
 'reduceOnly': None,
 'takeProfitPrice': None,
 'stopLossPrice': None}
```

As you can see, the amount and remaining computation are still wrong, and are confusing.
newSize and filled are correct though

**Comment by carlosmiei** [comment]
@KevinBaudin Can you please double-check your ccxt version? I tried to emulate that order event and got a different result (if you confirm it I will try to debug it using a real order)
![image](https://github.com/ccxt/ccxt/assets/43336371/46c68e93-1446-4c1b-a31a-35c155e0cee1)

**Comment by KevinBaudin** [comment]
Hi
I'll retry it today, it took me some tries to make it rehappen, I'll test my "luck" again :)

**Comment by KevinBaudin** [comment]
![image](https://github.com/ccxt/ccxt/assets/20791331/d52256d0-d37a-4d7e-af50-279f857a85fa)

This is not exactly the same issue, but there is again a negative remaining here.

**Comment by carlosmiei** [comment]
> ![image](https://private-user-images.githubusercontent.com/20791331/310059330-d52256d0-d37a-4d7e-af50-279f857a85fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzE1MDAsIm5iZiI6MTcwOTYzMTIwMCwicGF0aCI6Ii8yMDc5MTMzMS8zMTAwNTkzMzAtZDUyMjU2ZDAtZDM3YS00ZDdlLWFmNTAtMjc5Zjg1N2E4NWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5MzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZWU0MWNhNjhmNGVmNDMxN2I4MDkxZTZmN2IyMDAwYzE3MWE2NDlmYjNkZmY2MWVlZjRlNzIwZDk2YzU3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SwNTV-Up1t2Rn74mOs2oZwl6G404BBEd9Wff9SHtSYA)
> 
> This is not exactly the same issue, but there is again a negative remaining here.

Can you post the entire message in the text-format please?

**Comment by KevinBaudin** [comment]
Sorry I lost it, but I got another one:

```
[{'info': {'instId': 'DOGEUSDT',
   'orderId': '1148842444827561992',
   'clientOid': 'aa53817b-b68d-4d55-aa70-a7c149897017',
   'size': '23.6600',
   'newSize': '23.6600',
   'notional': '23.660000',
   'orderType': 'market',
   'force': 'gtc',
   'side': 'buy',
   'fillPrice': '0.180806',
   'tradeId': '1148842445283729530',
   'baseVolume': '130.8584',
   'fillTime': '1709631304093',
   'fillFee': '-0.1308584',
   'fillFeeCoin': 'DOGE',
   'tradeScope': 'T',
   'accBaseVolume': '130.8584',
   'priceAvg': '0.180806',
   'status': 'partially_filled',
   'cTime': '1709631303984',
   'uTime': '1709631304118',
   'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.1308584'}],
   'enterPointSource': 'API'},
  'symbol': 'DOGE/USDT',
  'id': '1148842444827561992',
  'clientOrderId': 'aa53817b-b68d-4d55-aa70-a7c149897017',
  'timestamp': 1709631303984,
  'datetime': '2024-03-05T09:35:03.984Z',
  'lastTradeTimestamp': 1709631304118,
  'type': 'market',
  'timeInForce': 'GTC',
  'postOnly': False,
  'side': 'buy',
  'price': 0.180806,
  'stopPrice': None,
  'triggerPrice': None,
  'amount': 130.8584,
  'cost': 23.66,
  'average': 0.180806,
  'filled': 130.85848920942888,
  'remaining': -8.9209428890634e-05,
  'status': 'open',
  'fee': {'cost': '0.1308584', 'currency': 'DOGE'},
  'trades': [],
  'fees': [{'cost': 0.1308584, 'currency': 'DOGE'}],
  'lastUpdateTimestamp': None,
  'reduceOnly': None,
  'takeProfitPrice': None,
  'stopLossPrice': None}]
```

A bit less problematic. I'll try to get another one

**Comment by carlosmiei** [comment]
@KevinBaudin I managed to reproduce the issue using the last log

**Comment by carlosmiei** [comment]
I think I will remove this

```
        if (market['spot'] && (rawStatus !== 'live')) {
            filled = Precise.stringDiv(cost, avgPrice);
        }
```
it's causing the remaining issue
