### ISSUE TITLE
Mexc cancel_all_orders returns with "ccxt\ExchangeError  mexc {"code":700013,"msg":"Invalid content Type."}."

### ISSUE THREAD

**Issue by szwagros** [ccxt/ccxt#21505]
### Operating System

Linux

### Programming Languages

PHP

### CCXT Version

4.1.34

### Description

Calling $exchange->cancel_all_orders(symbol) on mexc exchange returns 

 ccxt\ExchangeError  mexc {"code":700013,"msg":"Invalid content Type."}.

error message. Orders are not canceld on exchange.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @szwagros, if you update your ccxt version, that issue should be fixed by now.

**Comment by szwagros** [comment]
Hi,
at first composer updated ccxt to 4.1.34. Now I've update ccxt to 4.2.58 along with bunch of react packages and problem still exists. Every call to cancel_all_orders on mexc ends up with {"code":700013,"msg":"Invalid content Type."} message

**Comment by carlosmiei** [comment]
@szwagros Can you enable the verbose log and check the headers to see if the content-type is there?

**Comment by szwagros** [comment]
@carlosmiei probably because of this:

https://github.com/ccxt/ccxt/blob/master/php/mexc.php#L5420

it only adds this header for POST/PUT but not for DELETE which is used for cancel_all_orders.

**Comment by carlosmiei** [comment]
@szwagros I will add it asap (for some reason I can't reproduce)

**Comment by carlosmiei** [comment]
@szwagros Can you update your ccxt version and try again? We just released a new version with the suggested patch.

**Comment by szwagros** [comment]
I've upgraded to 4.2.59 and now everthing works fine ! Thank you!


```
Array
(
    [0] => fetch Request:
    [1] => mexc
    [2] => DELETE
    [3] => https://api.mexc.com/api/v3/openOrders?symbol=GHXUSDT&timestamp=1709562973982&recvWindow=5000&signature=xxxx
    [4] => RequestHeaders:
    [5] => Array
        (
            [0] => X-MEXC-APIKEY: xxxxxx
            [1] => source: CCXT
            [2] => Content-Type: application/json
            [3] => X-HTTP-Method-Override: DELETE
        )

    [6] => RequestBody:
    [7] => 
)

```
