### ISSUE TITLE
Looping through orders in C#

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21560]
### Programming Languages

Python

### CCXT Version

4.2.58

### Description

In python, it is possible to do 
`orders = exchange.orders`
this gives a list of orders, of length 'ordersLimit' that is passed in the exchange options. 
I tried to do this in C#
```
Dictionary<string, object> orders = (Dictionary<string, object>) exchange.orders;
List<object> orders = (List<object>) exchange.orders;
```
But neither works. I get 
`Unable to cast object of type 'ccxt.pro.ArrayCacheBySymbolById' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.`

How could I do please?
 

### Code

```
  

```

**Comment by carlosmiei** [comment]
@nikky78 Did you find the solution?

**Comment by nikky78** [comment]
Yep I did, I just needed to use IList instead of List

**Comment by carlosmiei** [comment]
@nikky78 I will try to type this structure to make this more clear

**Comment by carlosmiei** [comment]
@nikky78 We published, can you please update your ccxt version and try again?

**Comment by nikky78** [comment]
Updated to 4.2.64 and I still do not received messages. I am on bybit testnet.
