### ISSUE TITLE
HitBTC fetch_ohlcv not supporting since parameter

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#21646]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.65

### Description

When I try to retrieve historical data for HitBTC using the since parameter it always returns the most recent datapoints. The API does seem to support since see: https://api.hitbtc.com/#candles.

### Code

```
  
client = ccxt.hitbtc()

ticker = "BTCUSDT"
start = int(time.time() * 1000 - 60000 * 1440 * 30)

data = client.fetch_ohlcv(ticker, '1m', since=int(start))

print(start)
print(data[0][0])
```
1707481068487
1710066600000

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, thanks for reporting it we will check it asap

**Comment by carlosmiei** [comment]
@Tomas-MP Can you please update to the latest version and try again? Should be working now

**Comment by Tomas-MP** [comment]
Not working in version 4.2.66 based on the code above.

**Comment by Tomas-MP** [comment]
@carlosmiei it is still not working somehow in version 4.2.74, do you have any idea how I can solve this on my end?
