### ISSUE TITLE
'params.until' parameter not taken into account in fetchOHLCV for coinbasepro

### ISSUE THREAD

**Issue by lo-zed** [ccxt/ccxt#22191]
### Operating System

x86_64 GNU/Linux

### Programming Languages

Python

### CCXT Version

4.2.100

### Description

using method fetchOHLCV on a coinbasepro exchange object always returns the latest candles without taking into account the `params.until` parameter.

I tried using string instead of int, changing to ms. Nothing I tried changed anything on the results.

### Code

```python
from datetime import datetime, timezone

import ccxt

exchange = ccxt.coinbasepro({'apiKey': ...})

until = datetime.now(timezone.utc).timestamp() - 1800
echange.fetch_ohlcv('BTC/USDT', timeframe='5m', limit=2, params={'until': int(until)})  # wrong -> returns latest candles
exchange.public_get_products_id_candles({'id': 'BTC-USDT', 'granularity': '300', 'start': str(int(until - 600)), 'end': str(int(until))})  # correct
```

**Comment by samgermain** [comment]
`params.until` is not implemented universally yet, normally I implement it once someone shows that they want it, but coinbase deprecated pro in favour of coinbase advanced trade. CCXT members have tried to delist coinbasepro a few times, but those changes have been reverted. I can't remember why, but there was still use for the coinbasepro class

**Comment by lo-zed** [comment]
no wait, actually `start` is after `end`: 1713428452 > 1713426112.266

now if I define `since = until - 600`, I get
```python
exchange.fetch_ohlcv('BTC/USDT', timeframe='5m', since=int(since * 1000), params={'until': int(until * 1000)})
ccxt.base.errors.RequestTimeout: coinbase GET https://api.coinbase.com/api/v3/brokerage/products/BTC-USDT/candles?granularity=FIVE_MINUTE&start=1713425512&end=1713426112266
```
This time the times are correct but `start` is still in seconds.

If I try to put `start` in ms
```python
exchange.fetch_ohlcv('BTC/USDT', timeframe='5m', since=int(since * 1e6), params={'until': int(until * 1000)})
ccxt.base.errors.BadRequest: coinbase {"error":"INVALID_ARGUMENT","error_details":"start and end argument is invalid - number of candles requested should be less than 300 ","message":"start and end argument is invalid - number of candles requested should be less than 300 "}
```
So apparently, the numbers were correct. Any idea why I get a timeout?

**Comment by lo-zed** [comment]
as a workaround I use `since` instead of `params.until` like so (e.g. for 5m=300s):
```python
since = until - 300 * limit * 1e3
```

**Comment by samgermain** [comment]
So your issue is solved then?

**Comment by lo-zed** [comment]
no, the issue remains, `params.until` does not work on coinbase either. But it is possible to have the same behaviour as desired by combining `since` and `limit`

**Comment by samgermain** [comment]
> no, the issue remains, `params.until` does not work on coinbase either. But it is possible to have the same behaviour as desired by combining `since` and `limit`

It does not work because `params.until` is not implemented universally. You can check the docstring of a method to see if until has been implemented for that method on that exchange
