### ISSUE TITLE
PHP Binance: Argument #2 ($reason) must be of type string, null given

### ISSUE THREAD

**Issue by indigoram89** [ccxt/ccxt#22857]
### Operating System

MacOS

### CCXT Version

4.3.48

### Description

$http_status_text can be null

![CleanShot 2024-06-20 at 14 51 34@2x](https://github.com/ccxt/ccxt/assets/85135210/06bbed4f-034c-488a-bf6b-b0abc1221491)

Then it passes to handle_errors method

![CleanShot 2024-06-20 at 14 52 33@2x](https://github.com/ccxt/ccxt/assets/85135210/7ed8176e-9cd0-4fe0-abb7-c414564d1c3d)

But binance accepts only string

![CleanShot 2024-06-20 at 14 53 24@2x](https://github.com/ccxt/ccxt/assets/85135210/ff67e056-f0e8-4db7-a09f-6ababc39ab89)

As result the error

TypeError: ccxt\binance::handle_errors(): Argument #2 ($reason) must be of type string, null given, called in /vendor/ccxt/ccxt/php/Exchange.php on line 1637 and defined in /vendor/ccxt/ccxt/php/binance.php:10939

### Code

```
  

```

**Comment by carlosmiei** [comment]
@indigoram89 Can you please update your ccxt version and try again? should be working now

**Comment by gituser** [comment]
@indigoram89 @sc0Vu 
Hello! This bug is still present in the release [4.3.49](https://github.com/ccxt/ccxt/releases/tag/4.3.49) where you think you've fixed it.

The error happens inside `function handle_errors`, when e.g. binance replies with empty body or null.

Because you have `string $body` and instead of string null body sent to that function:

```
/vendor/ccxt/ccxt/php/binance.php in ccxt\binance::handle_errors at line 10936

            return $this->safe_dict($exceptionsForMarketType, $exactOrBroad, array());
        }
        return array();
    }
    public function handle_errors(int $code, string $reason, string $url, string $method, array $headers, string $body, $response, $requestHeaders, $requestBody) {
        if (($code === 418) || ($code === 429)) {
            throw new DDoSProtection($this->id . ' ' . (string) $code . ' ' . $reason . ' ' . $body);
        }
        // $error $response in a form => array( "code" => -1013, "msg" => "Invalid quantity." )
        // following block cointains legacy checks against $message patterns in "msg" property```

**Comment by carlosmiei** [comment]
@gituser sorry, we will take a look again

**Comment by carlosmiei** [comment]
@gituser can you please update and try again? now I believe it should be working

**Comment by gituser** [comment]
@carlosmiei thank you for the quick fix!
I've updated ccxt version to the latest one 4.3.51 will report back if there are any more errors like that.

**Comment by carlosmiei** [comment]
@gituser I will close this issue, but please feel free to reopen it if you need anything!

**Comment by gituser** [comment]
> @gituser I will close this issue, but please feel free to reopen it if you need anything!

Hello! There is a similar error in the kraken exchange and maybe other exchanges as well:

```
ccxt\kraken::handle_errors(): Argument #6 ($body) must be of type string, null given, called in vendor/ccxt/ccxt/php/Exchange.php on line 1638
```

**Comment by gituser** [comment]
> @gituser hum very weird, can you please ensure the ccxt version is the correct one? Right now I don't see how the body can be null here. What's the best way of reproducing this issue?

The ccxt version is `4.3.51`.

This error happens sometimes when I try to fetch the balance via kraken's `fetch_balance()` function: https://github.com/ccxt/ccxt/blob/master/php/kraken.php#L1320

**Comment by carlosmiei** [comment]
@gituser are you using the `sync` or `async` version?

**Comment by gituser** [comment]
@carlosmiei 
> @gituser are you using the `sync` or `async` version?
I'm using the `sync` version.

**Comment by carlosmiei** [comment]
@gituser I'm running this snippet but couldn't reproduce it yet, do you know if there's an easier way?

```Php
    while (true) {
        $i++;
        $balance = $exchange->fetch_balance();
        print_r($balance);
        print("Iteration: $i\n");
        sleep(1);
    }
```
