### ISSUE TITLE
Can't fetch deposit address for POL in OKX

### ISSUE THREAD

**Issue by abo-take** [ccxt/ccxt#23875]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

ccxt==4.3.68

### Description

Trying to fetch deposit POL address in MATIC network from OKX, but got error:
`okx fetchDepositAddress() cannot find Polygon deposit address for POL`

1) It works fine for other exchanges. 
2) I double checked network name with fetch_currencies() and it's definitely MATIC

My code:

### Code

```
  address_info = await self.exchange.create_deposit_address(currency, params={'network': network}) 
```

**Comment by carlosmiei** [comment]
Hello @abo-take,

Are you sure the address is created on the exchange side?

If you enable the verbose mode (exchange.verbose = True) can you see the address in the raw response?

**Comment by abo-take** [comment]
@carlosmiei 

Request: :` fetch Response: okx GET https://www.okx.com/api/v5/asset/deposit-address?ccy=POL 200`

Response: `ResponseBody: {"code":"0","data":[{"chain":"POL-ERC20","ctAddr":"ffc3f6","ccy":"POL","to":"6","verifiedName":"","addr":"0x155f74d5ab8922589e8a42c5c5dac5eda1ea2595","selected":true},{"chain":"POL-ERC20","ctAddr":"ffc3f6","ccy":"POL","to":"6","verifiedName":"","addr":"0x956119df7f850c530a1b6b86a73eb774e6c60196","selected":false},{"chain":"POL-ERC20","ctAddr":"ffc3f6","ccy":"POL","to":"6","verifiedName":"","addr":"0x17fc7a8e542a38eb911c2d8b1e0cb7af5c9d8b17","selected":false},{"chain":"POL-ERC20","ctAddr":"ffc3f6","ccy":"POL","to":"6","verifiedName":"","addr":"0xf4c3856f52d55377c21abd268640027584cda4c2","selected":false},{"chain":"POL-Polygon","ctAddr":"","ccy":"POL","to":"6","verifiedName":"","addr":"0x155f74d5ab8922589e8a42c5c5dac5eda1ea2595","selected":true},{"chain":"POL-Polygon","ctAddr":"","ccy":"POL","to":"6","verifiedName":"","addr":"0x956119df7f850c530a1b6b86a73eb774e6c60196","selected":false},{"chain":"POL-Polygon","ctAddr":"","ccy":"POL","to":"6","verifiedName":"","addr":"0x17fc7a8e542a38eb911c2d8b1e0cb7af5c9d8b17","selected":false},{"chain":"POL-Polygon","ctAddr":"","ccy":"POL","to":"6","verifiedName":"","addr":"0xf4c3856f52d55377c21abd268640027584cda4c2","selected":false}],"msg":""}`

**Comment by abo-take** [comment]
> Hello @abo-take,
> 
> Are you sure the address is created on the exchange side?


I believe it should create new address in this case, isn't it?
 Anyway, when I try to do it manually with `create_deposit_address()` I got this message: `okx createDepositAddress() is not supported yet`

**Comment by abo-take** [comment]
Also, if it helps, the same error trying to fetch `ATOM `deposit address (using network parameter: `ATOM`)

**Comment by carlosmiei** [comment]
@abo-take Yes okx does not provide a `create_deposit_address` endpoint, so I'm wondering whether you have to go the WEB UI and create the deposit address manually or not

**Comment by carlosmiei** [comment]
@abo-take Wait, actually I think I found an issue in the way networks are returned there, checking it rn

**Comment by carlosmiei** [comment]
@abo-take Can you please upgrade your ccxt version and try again? it should be working now

**Comment by abo-take** [comment]
Hi @carlosmiei,
I can confirm that now it works for POL address in Polygon network.
But still have an error trying to pull ATOM address in ATOM network : `An error occurred: okx fetchDepositAddress() cannot find ATOM deposit address for ATOM`

**Comment by abo-take** [comment]
Hi @carlosmiei,
Thank you for a quick fix. It works now.
