### ISSUE TITLE
Bybit's decimal precision is incorrect

### ISSUE THREAD

**Issue by llchkhutiashvili** [ccxt/ccxt#25269]
### Operating System

Ubuntu 22.04 LTS

### Programming Languages

Python

### CCXT Version

4.4.52

### Description

When trading on Bybit, creating an order for DOGE/USDT incorrectly rounds DOGE to whole numbers and USDT to just one decimal place. This is inaccurate because DOGE supports one decimal place, while USDT allows four to five decimal places.

### Code

```   

 params = {
            'category': 'spot',
        }
 response= exchange.create_order("DOGE/USDT","market","buy",4.2222,params=params)
  

```

**Comment by llchkhutiashvili** [comment]
Only tested for DOGE/USDT, but could be problem for other pairs too

**Comment by Dan-krm** [comment]
Hi @llchkhutiashvili I've opened a pull request that should resolve this issue, spot market buy orders where only the amount is defined was using cost precision instead of amount precision. Here is the relevant block of code:
```
else if (market['spot'] && (type === 'market') && (side === 'buy')) {
    // classic accounts
    // for market buy it requires the amount of quote currency to spend
    let createMarketBuyOrderRequiresPrice = true;
    [ createMarketBuyOrderRequiresPrice, params ] = this.handleOptionAndParams (params, 'createOrder', 'createMarketBuyOrderRequiresPrice');
    if (createMarketBuyOrderRequiresPrice) {
        if ((price === undefined) && (cost === undefined)) {
            throw new InvalidOrder (this.id + ' createOrder() requires the price argument for market buy orders to calculate the total cost to spend (amount * price), alternatively set the createMarketBuyOrderRequiresPrice option or param to false and pass the cost to spend in the amount argument');
        } else {
            const quoteAmount = Precise.stringMul (amountString, priceString);
            const costRequest = (cost !== undefined) ? cost : quoteAmount;
            request['qty'] = this.getCost (symbol, costRequest);
        }
    } else {
        if (cost !== undefined) {
            request['qty'] = this.getCost (symbol, this.numberToString (cost));
        } else if (price !== undefined) {
            request['qty'] = this.getCost (symbol, Precise.stringMul (amountString, priceString));
        } else {
            request['qty'] = amountString; // EDITED LINE
        }
    }
}
```

Let me know if you see any other problems or if you are still having issues after this edit is merged.

**Comment by llchkhutiashvili** [comment]
@Dan-krm Hello,
I am using UTA Account and issue still persist

    params = {
            'category': 'spot',
            'marketUnit':"quoteCoin"
        }
    response= exchange.create_order("DOGE/USDT","market","buy",4.22222,params=params)

I think problem is here 

        print(amount,"before converting")
        amountString = self.get_amount(symbol, amount)
        # amountString = self.number_to_string(amount)
        print(amountString)

4.22222 before converting
4.2


If you are not planning to make major developments for the UTA account type, I think, from my side, it would be best to round values based on symbols and then convert the number to a string.

**Comment by Dan-krm** [comment]
@llchkhutiashvili it looks like this is expected behavior. When placing an order like this `exchange.create_order("DOGE/USDT","market","buy",4.22222,params=params)` it converts the amount to 4 which is correct because the exchange expects whole numbers for that trading pair when using doge:

![Image](https://github.com/user-attachments/assets/b74b24c3-6bad-48bb-9e26-4a0369a8f3ae)

The basePrecision being used is 1 for that trading pair:
```
{
  symbol: 'DOGEUSDT',
  baseCoin: 'DOGE',
  quoteCoin: 'USDT',
  innovation: '0',
  status: 'Trading',
  marginTrading: 'none',
  stTag: '1',
  lotSizeFilter: {
    basePrecision: '1',
    quotePrecision: '0.00000000000001',
    minOrderQty: '0.1',
    maxOrderQty: '66666666.6666666666666667',
    minOrderAmt: '0.1',
    maxOrderAmt: '2000000'
  },
  priceFilter: { tickSize: '0.00000000000001' },
  riskParameters: { priceLimitRatioX: '0.1', priceLimitRatioY: '0.1' }
}
```

When placing an order using the quote asset by setting the 'cost' parameter it has the correct behavior as well:
`create_order("DOGE/USDT","market","buy",None,None,params={"cost":4.12345678901234)`
after the conversion in the getCost helper method the amount is still `4.12345678901234`

![Image](https://github.com/user-attachments/assets/0524fcf8-e430-4adb-a417-becef145ed34)
