### ISSUE TITLE
error exchange.cancelOrder

### ISSUE THREAD

**Issue by stas087** [ccxt/ccxt#25459]
### Operating System

Windows

### CCXT Version

4.4.35

### Description

Hello! When canceling a stop order on the HTX exchange using await exchange.cancelOrder(order_id, pair);, the following error message is returned:
 info: {
    status: 'ok',
    data: { errors: [Array], successes: '' },
    ts: '1741766585889'
  },
  id: '1349412232274620416',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'ADA/USDT:USDT',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: 'canceled',
  reduceOnly: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  lastUpdateTimestamp: undefined,
  stopPrice: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}

### Code

async function cancelStopOrder(order_id) {
    try {
		const response = await exchange.cancelOrder(order_id, pair);
        console.log( response);
		console.log(response.info.data.errors)
        return response;
    } catch (error) {
        console.error(error.message);
        throw error;
    }
}
  

```

**Comment by carlosmiei** [comment]
Hello @stas087,  thanks for reporting it. 

Can you post the verbose log? `exchange.verbose = true` so we can see the raw HTTP message?

**Comment by stas087** [comment]
Did I provide enough of the log? Is this sufficient?

**Comment by carlosmiei** [comment]
Hello @stas087, yes that is enough, basically we need to adjust our error-handling logic to throw an error when such message is received. We will do it shortly.

**Comment by carlosmiei** [comment]
@stas087 Can you please upgrade and try again? it should be working now

**Comment by stas087** [comment]
I updated it, but the stop order still doesn't get canceled:

\ 10:59:17ADA/USDT:USDT     qty:3128696.000 @ 0.734675       pnl:0.846fetch Request:
 htx POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_cancel?AccessKeyId=c4a0b729-5d4664ba-b4c3b3aa-vqgdf4gsga&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2025-03-13T01%3A59%3A21&Signature=Hg5Q571Jaqb0RgAG0VjFAdd4Lj%2FcP%2B2aOihgB41O3BA%3D
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
  'Content-Type': 'application/json'
}
RequestBody:
 {"order_id":"1349683231270170624","contract_code":"ADA-USDT"}

| 10:59:17ADA/USDT:USDT     qty:3128696.000 @ 0.734675       pnl:0.846handleRestResponse:
 htx POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_cancel?AccessKeyId=c4a0b729-5d4664ba-b4c3b3aa-vqgdf4gsga&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2025-03-13T01%3A59%3A21&Signature=Hg5Q571Jaqb0RgAG0VjFAdd4Lj%2FcP%2B2aOihgB41O3BA%3D 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '91f7ee7eda155e01-HKG',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'text/plain;charset=UTF-8',
  Date: 'Thu, 13 Mar 2025 01:59:22 GMT',
  Expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  Pragma: 'no-cache',
  'Ratelimit-Interval': '3000',
  'Ratelimit-Limit': '72',
  'Ratelimit-Remaining': '71',
  'Ratelimit-Reset': '1741831165737',
  Reqid: 'b69741d4ab70f785fbf5db9a85133fc2',
  'Request-Id': 'b9237226f6d0f08bb8197778a2553c50',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  'X-Request-Id': 'b69741d4ab70f785fbf5db9a85133fc2'
}
ResponseBody:
 {"status":"ok","data":{"errors":[{"order_id":"1349683231270170624","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741831162739}

Ошибка при отмене ордера: htx {"status":"ok","data":{"errors":[{"order_id":"1349683231270170624","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741831162739}
file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4686
            throw new exact[string](message);
                  ^

OrderNotFound: htx {"status":"ok","data":{"errors":[{"order_id":"1349683231270170624","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741831162739}
    at htx.throwExactlyMatchedException (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4686:19)
    at htx.handleErrors (file:///D:/JS%20modules/node_modules/ccxt/js/src/htx.js:7636:18)
    at file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:693:51
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async htx.fetch2 (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4208:24)
    at async htx.request (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4230:16)
    at async htx.cancelOrder (file:///D:/JS%20modules/node_modules/ccxt/js/src/htx.js:6015:36)
    at async cancelStopOrder (file:///D:/JS%20modules/index.js:648:20)

Node.js v22.13.0

**Comment by stas087** [comment]
Still getting an error:

fetch Request:
 htx POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_trigger_cancel?AccessKeyId=c4a0b729-5d4664ba-b4c3b3aa-vqgdf4gsga&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2025-03-13T11%3A18%3A02&Signature=L2D5XEZgAtyVIF9YznnRcw%2FkQmn7NRMd3Alph9FMcQQ%3D
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
  'Content-Type': 'application/json'
}
RequestBody:
 {"order_id":"1349823831336513536","contract_code":"ADA-USDT"}

-  8:17:59ADA/USDT:USDT     qty:3280708.000 @ 0.722937      pnl:-19.937handleRestResponse:
 htx POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_trigger_cancel?AccessKeyId=c4a0b729-5d4664ba-b4c3b3aa-vqgdf4gsga&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2025-03-13T11%3A18%3A02&Signature=L2D5XEZgAtyVIF9YznnRcw%2FkQmn7NRMd3Alph9FMcQQ%3D 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '91fb20df1fd308f9-HKG',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'text/plain;charset=UTF-8',
  Date: 'Thu, 13 Mar 2025 11:18:03 GMT',
  Expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  Pragma: 'no-cache',
  'Ratelimit-Interval': '1000',
  'Ratelimit-Limit': '5',
  'Ratelimit-Remaining': '4',
  'Ratelimit-Reset': '1741864684419',
  Reqid: '548da3679d6c88c12aa8922212b48a52',
  'Request-Id': 'a707f18b5b8d97449cdf310e9e0e3a2d',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  'X-Request-Id': '548da3679d6c88c12aa8922212b48a52'
}
ResponseBody:
 {"status":"ok","data":{"errors":[{"order_id":"1349823831336513536","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741864683421}

htx {"status":"ok","data":{"errors":[{"order_id":"1349823831336513536","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741864683421}
file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4686
            throw new exact[string](message);
                  ^

OrderNotFound: htx {"status":"ok","data":{"errors":[{"order_id":"1349823831336513536","err_code":1061,"err_msg":"The order does not exist."}],"successes":""},"ts":1741864683421}
    at htx.throwExactlyMatchedException (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4686:19)
    at htx.handleErrors (file:///D:/JS%20modules/node_modules/ccxt/js/src/htx.js:7636:18)
    at file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:693:51
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async htx.fetch2 (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4208:24)
    at async htx.request (file:///D:/JS%20modules/node_modules/ccxt/js/src/base/Exchange.js:4230:16)
    at async htx.cancelOrder (file:///D:/JS%20modules/node_modules/ccxt/js/src/htx.js:6006:36)
    at async cancelStopOrder (file:///D:/JS%20modules/index.js:648:20)

Node.js v22.13.0

User@DESKTOP-S9TK59E C:\Users\User

**Comment by stas087** [comment]
To cancel stop orders (Take Profit/Stop Loss, TPSL) on HTX, you must use the dedicated API endpoint:
**POST /api/v1/contract_tpsl_cancelall**

**Comment by carlosmiei** [comment]
Hello @stas087 

Yes, you can also call `cancel_order` and provide `stopLossTakeProfit: true` in `params`  as you can see here:

https://docs.ccxt.com/#/exchanges/htx?id=cancelorder


![Image](https://github.com/user-attachments/assets/68509d1b-1ff7-4730-807d-2ec3a480d69a)

**Comment by stas087** [comment]
Thank you, [carlosmiei](https://github.com/carlosmiei)!
