### ISSUE TITLE
[Lbank] use WatchOrderBook to get data fail

### ISSUE THREAD

**Issue by LawrenceLai1107** [ccxt/ccxt#26934]
### Operating System

windows 10

### Programming Language

C#

### CCXT Version

4.5.5

### Description

We use WatchOrderBook to get info:

'''

      string symbol = "BTC/USDT";
      try
      {
          while (true)
          {
              ccxt.pro.IOrderBook odBook = await lbankPriceData.WatchOrderBook(symbol, 1);            
          }
      }
      catch (Exception ex)
      {
          Console.WriteLine(ex.Message);
      }

'''

It will cause an exception:

'''

      One or more errors occurred. (Value cannot be null. (Parameter 'key'))
      Initial completed 0 out of 0 tasks;

'''

**Comment by rayBastard** [comment]
Hi @LawrenceLai1107 ! Thank you, we'll check it asap!

**Comment by rayBastard** [comment]
@LawrenceLai1107 I tested on C# and yeah, the error appeared. We'll find what's wrong and solve the problem.

**Comment by rayBastard** [comment]
Hi @LawrenceLai1107 we fixed the bug! Will be in a nearest update.

**Comment by LawrenceLai1107** [comment]
Hi @rayBastard :
We're using ccxt version 4.5.10, but we still encounter errors on the LBANK exchange.
The example code is as follows:

`

            var lbankEx = new ccxt.pro.lbank( new Dictionary<string, object>() { });
            string symbol = "ETH/USDT:USDT";
            try
            {
                while (true)
                {
                    ccxt.pro.IOrderBook odBook = await lbankPriceData.WatchOrderBook(symbol, 1);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
`



`
    Object reference not set to an instance of an object.
`

**Comment by rayBastard** [comment]
Hi @LawrenceLai1107 : I will check it asap
