### ISSUE TITLE
fetchMyTrades(symbol) returns all trades on Kraken

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#2746]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.10.167
- Exchange: Kraken
- Method: fetchMyTrades(symbol)

fetchMyTrades(symbol) returns all trades on Kraken instead of the trades of the selected symbol.

**Comment by kroitor** [comment]
Fixed in most recent ccxt 1.13.83. Thx!
P.S. You version is too old, i'd recommend updating anyway.

**Comment by aking7** [comment]
This is still broken. Kraken still returns the trade history for all symbols, not just the one chosen. The fix just mislabels all the other trades as the incorrect symbol.
