### ISSUE TITLE
dydx create_order raise NameError("name 'Bip44' is not defined")

### ISSUE THREAD

**Issue by sdfwds4** [ccxt/ccxt#27600]
### Operating System

windows 11

### Programming Language

Python

### CCXT Version

4.5.30

### Description

<img width="1105" height="909" alt="Image" src="https://github.com/user-attachments/assets/a8793520-258f-44a6-acf5-c52145332fad" />

here my code:
```
import ccxt

def dydx_usage_example():

    exchange = ccxt.dydx({
        'walletAddress': 'dydx1aba4sedmwq304u2ku9pwzjwq0lu5z2s4tslxrs',
        'privateKey': '0x6c46cc6c20e92caa34f2c22a440a396949229c4690e44f2f290922fe4fc22cf4',

        'verbose': False,
    })

    print("✓ dydx init success\n")

    try:
        order = exchange.create_order(
            symbol="ETH-USD",
            type="market",
            side="buy",
            amount=0.001,
        )
        print("✓ oreder created successfully")
        print(f"   order: {order}")

    except Exception as e:
        print(f"✗ create_order error: {e}\n")


if __name__ == "__main__":
    dydx_usage_example()
```

**Comment by carlosmiei** [comment]
@sdfwds4 Thanks for reporting it we will take a look. Right now pls make sure the keys in your message aren't valid or move the funds out immediatly.

**Comment by carlosmiei** [comment]
@sdfwds4 We have merged a fix but it might take some time to release a new version, can you please try to manually update that import to `from ccxt.static_dependencies.bip.bip44 import Bip44` to see if that fixes the issue?

**Comment by sdfwds4** [comment]
@carlosmiei Changing it to `from ccxt.static_dependencies.bip.bip44 import Bip44` didn’t help—the same error still occurs. However, I’ve found the issue: the `pycryptodome` dependency needs to be installed.

**Comment by carlosmiei** [comment]
@sdfwds4 thanks for the feedback, @sc0Vu can you please check again?

**Comment by sc0Vu** [comment]
@sdfwds4 Thanks for reporting this. You're right about this, I'll add pycryptodom to static_dependencies asap.

**Comment by kroitor** [comment]
Hello @sdfwds4, closing this during a cleanup — the failure mode you hit is resolved on current versions, through a different route than vendoring: the old bip import chain is gone entirely, dydx signing goes through the bundled dydx_v4_client machinery, and the optional dependency imports are guarded now, so a missing package raises a clear NotSupported telling you exactly what to install, pip install "protobuf==5.29.5" and pycryptodome==3.18.0, instead of the cryptic import error you saw. Pycryptodome itself stays a deliberate optional install rather than a bundled dependency, since it is a compiled package that cannot be vendored the way the pure python dependencies are. And echoing carlosmiei from this thread: the wallet keys you posted here should be considered burned if they were ever real. Thanks for the report and for pinpointing the missing package yourself!
