### ISSUE TITLE
CoinFalcon improvements (fetch order, signing for GET/DELETE requests)

### ISSUE THREAD

**Issue by markhorner123** [ccxt/ccxt#3446]
Hey again

Some misc improvements for CoinFalcon that I've made in Python (there may be more elegant ways to do such things);

When making a GET or DELETE request, we're going to be needing to add the ID of the item we are get/delete to the end of our payload. Currently CCXT implements adding a structure of ?id=xxx where as CoinFalcon's API requires the URL and sign to be in the format of 
```/api/v1/user/orders/orderidhere```

As the signing process currently stands, we get a signature error due to the signed URL being in the format of;
```
https://coinfalcon.com/api/v1/user/orders/id=9c3fc438-d0bd-4fb1-9317-XXX
```

The URL needs to be updated so it reads;
```
https://coinfalcon.com/api/v1/user/orders/i9c3fc438-d0bd-4fb1-9317-XXX
```

We also need to update the Payload;
Currently it's generated as
```
1532095595|GET|/api/v1/user/orders
```

But we need it to also include the order ID when it's being signed in the format of;
```
1532095595|GET|/api/v1/user/orders/i9c3fc438-d0bd-4fb1-9317-XXX
```

The fix I have implemented for now on the signing side which will work for fetching/canceling an order is updating the sign method to the following (note I have only added a check to see if id in query keys, as per the docs the only time an 'id' is required is when it's the only param to be passed for private methods);
```
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        request = '/' + 'api/' + self.version + '/' + self.implode_params(path, params)
        url = self.urls['api'] + request
        query = self.omit(params, self.extract_params(path))
        if api == 'public':
            if query:
                url += '?' + self.urlencode(query)
        else:
            self.check_required_credentials()
            if method == 'GET' or method == 'DELETE':
                if query:
                    if 'id' in query.keys():
                        url += '/' + self.urlencode(query['id'])
                    else:
                        url += '/' + self.urlencode(query)
            else:
                body = self.json(query)
            seconds = str(self.seconds())
            payload = '|'.join([seconds, method, request])
            if body:
                payload += '|' + body
            if query:
                if 'id' in query.keys():
                    payload += '/' + query['id']
                else:
                    payload += '/' + query
            signature = self.hmac(self.encode(payload), self.encode(self.secret))
            headers = {
                'CF-API-KEY': self.apiKey,
                'CF-API-TIMESTAMP': seconds,
                'CF-API-SIGNATURE': signature,
                'Content-Type': 'application/json',
            }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
```

To implement fetch order the following method in Python works after the signing process has been updated slightly;

```
    def fetch_order(self, id, symbol=None, params={}):
        self.load_markets()
        response = self.privateGetUserOrders(self.extend({
            'id': id,
        }, params))
        market = self.market(symbol)
        return self.parse_order(response['data'], market)
```

**Comment by PoshElf** [comment]
Need this as well. Any ETA?

**Comment by kroitor** [comment]
@markhorner123 thx for a comprehensive report! However, the fix for it is a bit simpler because our URLs are actually templates, see here: https://github.com/ccxt/ccxt/commit/74f4df34fae15a3dcd0fab8e3a905e0962950c6d

@PoshElf should be fixed now in 1.17.14, let us know if you have further difficulties with it.

**Comment by markhorner123** [comment]
Hey @kroitor this isn't resolved - now the implementation for cancel order is raising;
response = self.privateDeleteUserOrders(self.extend({
AttributeError: 'coinfalcon' object has no attribute 'privateDeleteUserOrders'

Also can you update in the fetch_order implementation too, with adding the below method it's still raising similar error to the above for cancel_order implementation?
def fetch_order(self, id, symbol=None, params={}):
        self.load_markets()
        response = self.privateGetUserOrders(self.extend({
            'id': id,
        }, params))
        market = self.market(symbol)
        return self.parse_order(response['data'], market)

Have a feeling this might be a quick/simple one for you to resolve?

**Comment by kroitor** [comment]
@markhorner123 oh, sorry, that's a leftover, will fix for it right now.

**Comment by markhorner123** [comment]
Thank you - can you also add the fetch_order implementation :D?

**Comment by markhorner123** [comment]
Place, Fetch and Cancel orders all working fine - thx again for your help @kroitor
