### ISSUE TITLE
Problem with fetchDepositAddress on Kucoin v2

### ISSUE THREAD

**Issue by paxpelus** [ccxt/ccxt#4700]
Whilte trying to use kucoin v2 API I am trying to do 

const wallet = await exchange.fetchDepositAddress(tokenName);

I am getting this error
InvalidAddress - kucoin2 address is undefined

I tried to manually create the wallet through kucoin interface but the response is still the same.

I have created new API keys for kucoin v2 and added the extra password parameter.

- OS: Ubuntu
- Programming Language version: Javascript/Node
- CCXT version: 1.18.248
- Exchange: Kucoin
- Method: fetchDepositAddress

**Comment by kroitor** [comment]
@paxpelus 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```JavaScript
await exchange.loadMarkets ()
exchange.verbose = true
const wallet = await exchange.fetchDepositAddress(tokenName)
```

↑ Post your verbose request/response, plz.

> I tried to manually create the wallet through kucoin interface but the response is still the same.

Can you tell exactly the sequence of actions you've taken to create it through the KuCoin interface?

**Comment by paxpelus** [comment]
In order to create a wallet I went on https://www.kucoin.com/assets/coin and selected e.g. LALA coin and a new address was generated for me 


fetch:
 kucoin2 GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=LALA 
Request:
 { 'KC-API-KEY': 'aaaaaaaaaaaa',
  'KC-API-TIMESTAMP': '1550568452565',
  'KC-API-PASSPHRASE': 'aaaaaaaaaaaaaa',
  'KC-API-SIGN': '+aaaaaaaaaaaaaaaaaaaaaaaa' } 
 undefined 


handleRestResponse:
 kucoin2 GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=LALA 200 OK 
Response:
 { Date: 'Tue, 19 Feb 2019 09:27:32 GMT',
  'Content-Type': 'application/json;charset=UTF-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie':
   '__cfruid=14601b26079cd87a6c9c54f31118a6e70b47a1b3-1550568452; path=/; domain=.kucoin.com; HttpOnly',
  'X-Trace-Id': '9c88adea1a0ffed6',
  'X-Content-Type-Options': 'nosniff',
  'X-Xss-Protection': '1; mode=block',
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  Expires: '0',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4ab7b2bc99789cb3-AMS',
  'Content-Encoding': 'gzip' } 
 {"code":"200000","data":{"address":"0xdb7c564b9b2726128591da8818cbb5eaff78fd1c","memo":""}} 


I can see the wallet address in response but the 

await exchange.fetchDepositAddress(tokenName) triggers the catch(e) method with the error I pointed out earlier.

**Comment by kroitor** [comment]
@paxpelus this has been fixed here: https://github.com/ccxt/ccxt/issues/4689

Are you sure that you have the latest version?

```JavaScript
const ccxt = require('ccxt')
console.log (ccxt.version)  // ←-- add this to show your runtime version number
exchange = new ccxt.kucoin2 (...
```

Let us know if upgrading to the most recent version doesn't help.

**Comment by paxpelus** [comment]
I upgraded to version 1.18.248 few hours ago and on npm I still see v1.18.248 as latest.
https://www.npmjs.com/package/ccxt

I upgraded now on v1.1.8.249 
All seems to be working now - thanks for your help!

**Comment by kroitor** [comment]
> on npm I still see v1.18.248 as latest

Will fix that as well, 1.18.249 will arrive to NPM shortly. Thx for reporting!

**Comment by saikatharryc** [comment]
hey @kroitor  getting the same problem i guess, i'm using the latest version i.e [1.18.273].
here is my verbose output:
```
handleRestResponse:
 kucoin2 GET https://openapi-v2.kucoin.com/api/v1/currencies 200 OK 
Response:
 { Date: 'Wed, 20 Feb 2019 16:05:23 GMT',
  'Content-Type': 'application/json;charset=UTF-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': '__cfruid=a62b2eeeec645f98bfc1e8f5c4276352d2b60f03-1550678723; path=/; domain=.kucoin.com; HttpOnly',
  'X-Trace-Id': '8c8a5780b099c9d1',
  'X-Content-Type-Options': 'nosniff',
  'X-Xss-Protection': '1; mode=block',
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  Expires: '0',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4ac236e2cde58993-MAA',
  'Content-Encoding': 'gzip' } 
 {"code":"200000","data":[...]} 

fetch:
 kucoin2 GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=BTC 
Request:
 { 'KC-API-KEY': 'xxxxxxxx',
  'KC-API-TIMESTAMP': 'xxxxxxxx',
  'KC-API-PASSPHRASE': 'xxxxx',
  'KC-API-SIGN': 'xxxxxx=' } 
 undefined 

handleRestResponse:
 kucoin2 GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=BTC 200 OK 
Response:
 { Date: 'Wed, 20 Feb 2019 16:05:23 GMT',
  'Content-Type': 'application/json;charset=UTF-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': '__cfruid=a62b2eeeec645f98bfc1e8f5c4276352d2b60f03-1550678723; path=/; domain=.kucoin.com; HttpOnly',
  'X-Trace-Id': '1d6840ade05b8391',
  'X-Content-Type-Options': 'nosniff',
  'X-Xss-Protection': '1; mode=block',
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  Expires: '0',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4ac236e4d96489b7-MAA',
  'Content-Encoding': 'gzip' } 
 {"code":"200000"} 

{ Error: kucoin2 address is undefined
    at kucoin2.checkAddress (/Users/astra/Desktop/eraswap_backend/node_modules/ccxt/js/base/Exchange.js:406:19)
    at kucoin2.fetchDepositAddress (/Users/astra/Desktop/eraswap_backend/node_modules/ccxt/js/kucoin2.js:497:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidAddress] }
```

**Comment by paxpelus** [comment]
From my experience I found out that you need to first manually create the wallet address in kucoin and then it should work through ccxt

You may use the createDepositAddress method - but I haven't experimented yet with that so I am not sure if it works fine for kucoin.

**Comment by saikatharryc** [comment]
@paxpelus  yes you were right, but unfortunately `createDepositAddress` doesnot work .
@kroitor  will there be any support for `createDepositAddress()` any sooner?

**Comment by kroitor** [comment]
@saikatharryc we usually add support for it as soon as the exchange adds the corresponding endpoint, so, it's not on our side, but more so on the KuCoin side. We've retransmitted your request to add to the wishlist to the KuCoin team, and you might want to address your question to their tech support as well.
Also, in order to understand which methods are available, take a look at this:

- https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

<img width="1511" alt="screen shot 2019-02-20 at 19 24 55" src="https://user-images.githubusercontent.com/1294454/53107056-4ea59200-3545-11e9-9be3-66aa62d63cd3.png">

**Comment by saikatharryc** [comment]
@kroitor 
The Api Endpoint from Kucoin to create deposit address is already present here:
https://docs.kucoin.com/#deposits
and also i can see this here too https://github.com/ccxt/ccxt/blob/master/js/kucoin2.js#L97

**Comment by kroitor** [comment]
@saikatharryc ah! Thx for pointing that out, missed it, will add it shortly. Appreciate your attention!

**Comment by kroitor** [comment]
@saikatharryc @paxpelus added `createDepositAddress` in 1.18.276, it will be available for downloading in 5-10 minutes. Thx again for your help!
