### ISSUE TITLE
Poloniex fetch all open orders

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#476]
```
  File "/usr/local/lib/python3.6/site-packages/ccxt/async/poloniex.py", line 448, in fetch_open_orders
    orders = await self.fetch_orders(symbol, params)

  File "/usr/local/lib/python3.6/site-packages/ccxt/async/poloniex.py", line 392, in fetch_orders
    market = self.market(symbol)

  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 838, in market
    raise ExchangeError(self.id + ' does not have market symbol ' + str(symbol))

ccxt.base.errors.ExchangeError: poloniex does not have market symbol None
```

I'd like for poloniex to  return all open orders when I pass None as symbol. Roughly this:
```await self.exchange.private_post_returnopenorders({"currencyPair":"all"})```, just unified.

**Comment by kroitor** [comment]
@nmiculinic, we will add support for `"all"` shortly! Thx a lot!

**Comment by kroitor** [comment]
This issue is now resolved in 1.10.5. Let us knot if you have any difficulties with it. Thx!

**Comment by davidpodrebarac** [comment]
I tested this and it is not yet resolved. If you call poloniex's fetch open orders with no arguments, i.e. ```poloniex.fetch_open_orders()``` you would get nothing. The problem lies here(line 429 below):
```
            if market:
                if order['symbol'] == symbol:
                    result.append(order)
            else:
                result.append(order)
```

Here, symbol could be None and it would never match order's symbol: order['symbol']. I am using ccxt==1.10.9.

**Comment by kroitor** [comment]
@davidpodrebarac just a sec, will fix right away, thx!

**Comment by davidpodrebarac** [comment]
It works. Thanks! :)
