### ISSUE TITLE
Bitfinex: Bad request endpoint

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5171]
- OS: Windows
- Programming Language version: NodeJS 10.14.0
- CCXT version: Latest
- Exchange: Bitfinexv2
- Method: publicGetTickers

Using `bitfinexv2.publicGetTickers` doesn't seem to use the correct endpoint.
I'm using nock to mock the requests to the server and when using nock.log to get the requested URL I get the following requests:

- GET https://api.bitfinex.com:443/v2/auth/r/orders/{symbol}
- GET https://api.bitfinex.com:443/v2/auth/r/orders/tIOTETH/hist
- GET https://api.bitfinex.com:443/v1/mytrades

But not the one that's [defined on the Bitfinex API documentation](https://docs.bitfinex.com/v2/reference#rest-public-tickers) that is https://api-pub.bitfinex.com/v2/tickers

I'm using bitfinex like this:
```javascript
const bitfinexV2 = new CCXT["bitfinex2"]({ 
	apiKey: API_KEY,
	secret: SECRET
});

bitfinexV2.publicGetTickers({symbols: "tIOTETH"});
```

Can you shed some light to what's happening?
Thanks!

**Comment by kroitor** [comment]
@ibesora this has been fixed recently: 

- https://github.com/ccxt/ccxt/issues/5109
- https://github.com/ccxt/ccxt/pull/5115

If you update to the most recent version 1.18.566, it should work normally. Let us know if you still have difficulties with the most recent version of it.

**Comment by ibesora** [comment]
I'm on the latest version 1.18.566 and it's still happenning. 
`publicGetPlatformStatus` runs as expected but `publicGetTickers` keeps doing the same requests as I point on the issue.

**Comment by kroitor** [comment]
Unfortunately, I can't reproduce it on my side. 

Does this work and which version does it show?

```JavaScript
const ccxt = require('ccxt')
const bitfinex2 = new ccxt.bitfinex2 ({
    'enableRateLimit': true, // as required by the Manual
});

;(async () => {
    await bitfinex2.loadMarkets ()
    bitfinex2.verbose = true // ←---------- adding this will show the URL being requested
    const ticker = await bitfinex2.fetchTicker ('IOTA/ETH')
    console.log ('CCXT Version:', ccxt.version)
}) ()
```

Or use this example to test it:

```
mbp:ccxt igorkroitor$ node examples/js/cli bitfinex2 fetchTicker ETH/BTC --verbose
```

Let's make sure that your version is up to date, 1.18.566 or higher and check the URL in the verbose output.

**Comment by kroitor** [comment]
@ibesora this should work as well:

```
const ccxt = require('ccxt')
const bitfinex2 = new ccxt.bitfinex2 ({
    'enableRateLimit': true, // as required by the Manual
});

;(async () => {
    await bitfinex2.loadMarkets ()
    bitfinex2.verbose = true // ←---------- adding this will show the URL being requested
    const ticker = await bitfinex2.publicGetTickerSymbol ({'symbol':'tIOTETH'})
    console.log ('CCXT Version:', ccxt.version)
}) ()
```

**Comment by ibesora** [comment]
@kroitor Didn't know about the verbose option, that will be useful.
It is doing the request to the correct endpoint, when using mock I was still using the old domain `api.bitfinex.com` so it didn't match the new one and it was showing old requests.
Sorry for wasting your time.

**Comment by kroitor** [comment]
@ibesora 

> @kroitor Didn't know about the verbose option, that will be useful.

Yep, I'd also recommend to check out the [`cli.js` example](https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js) – very useful for debugging these things.

> It is doing the request to the correct endpoint, when using mock I was still using the old domain api.bitfinex.com so it didn't match the new one and it was showing old requests.


Good to know you've figured it out! )

> Sorry for wasting your time.

No worries! Let us know if you have any further difficulties! Will be happy to help )
