### ISSUE TITLE
Livecoin "invalid signature"

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#5252]
Hi, I'm having trouble debugging. I turned verbose on and everything looks good. I created a new API key and tried seeing if I was doing something wrong in the docs but everything seems OK.

Request: Array ( [0] => GET [1] => https://api.livecoin.net/exchange/order?0%5BorderId%5D=22XXX&0%5Btype%5D=SELL [2] => Array ( [0] => Api-Key: XX9tpFNu [1] => Sign: 9BCXX39C5 [2] => Content-Type: application/x-www-form-urlencoded [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 ) [3] => ) Response: Array ( [0] => GET [1] => https://api.livecoin.net/exchange/order?0%5BorderId%5D=229XXX&0%5Btype%5D=SELL [2] => 500 [3] => [4] => Array ( [server] => Array ( [0] => nginx ) [date] => Array ( [0] => Thu, 06 Jun 2019 14:28:36 GMT ) [content-type] => Array ( [0] => application/json ) [content-length] => Array ( [0] => 52 ) [connection] => Array ( [0] => keep-alive ) ) [5] => {"success":false,"errorMessage":"invalid signature"} ) 17:28:36: ccxt\ExchangeError: livecoin {"success":false,"errorMessage":"invalid signature"} in /home/n/public_html/ccxt-master/php/livecoin.php:881 Stack trace: #0 /home/n/public_html/ccxt-master/php/Exchange.php(1263): ccxt\livecoin->handle_errors(500, '', 'https://api.liv...', 'GET', Array, '{"success":fals...', Array) #1 /home/nilv7c073rie/public_html/ccxt-master/php/Exchange.php(1079): ccxt\Exchange->fetch('https://api.liv...', 'GET', Array, NULL) #2 /home/n/public_html/ccxt-master/php/Exchange.php(1083): ccxt\Exchange->fetch2('exchange/order', 'private', 'GET', Array, NULL, NULL) #3 [internal function]: ccxt\Exchange->request('exchange/order', 'private', 'GET', Array) #4 /home/n/public_html/ccxt-master/php/Exchange.php(2214): call_user_func_array(Array, Array) #5 /home/n/public_html/ccxt-master/php/livecoin.php(515): ccxt\Exchange->__call('privateGetExcha...', Array) #6 /home/n/public_html/ccxt-master/php/Exchange.php(1771): ccxt\livecoin->fetch_order(229XX, 'GIFT/BTC', Array) #7 /home/n/public_html/coinsnap/coinsnap.php(630): ccxt\Exchange->fetchOrder(229XXX, 'GIFT/BTC', Array) #8 /home/n/public_html/coinsnap/tickers.php(32): COINSNAP->getOrders('Livecoin') #9 {main}

- OS: linu
- Programming Language version: php
- CCXT version: latest
- Exchange: livecoin
- Method: fetchOrder

**Comment by presence35** [comment]
So it's a bug and I should wait for a fix?

**Comment by kroitor** [comment]
> So it's a bug 

Yep

> and I should wait for a fix?

Nope ) Because it's already fixed in 1.18.637 ) So, you don't have to wait anymore, just update to the most recent version and that's it. Let us know if that doesn't help.

**Comment by presence35** [comment]
Weird... I downloaded the latest version just today.   Maybe I unzipped it
wrong or something.

**Comment by kroitor** [comment]
> Weird... I downloaded the latest version just today.   Maybe I unzipped it
wrong or something.

No, you downloaded the latest version (which had a bug in it) today, but then it was fixed (30 minutes before now) and you have to update again. )

**Comment by presence35** [comment]
Oh, haha, ok, glad it wasn't me...thanks for letting me know and for your
hard work :)

**Comment by presence35** [comment]
I upgraded just now to v1.18.641 but I'm still getting the same error.

**Comment by kroitor** [comment]
@presence35 make sure your runtime version is really up to date:

```PHP
echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";
```

↑ what does it say?

**Comment by presence35** [comment]
CCXT v.1.18.641

**Comment by kroitor** [comment]
@presence35 

I've tried with my key, and it didn't work (it said the key is wrong), and i had to recreate it, looks like livecoin has dropped it silently. Can you check if the key you're using corresponds to the one on the website?

It works for several developers with 1.18.641 on our side.

**Comment by presence35** [comment]
I'm using the right key for sure. I changed it to the wrong one and I get
error "incorrect key", but when I use the right one it says "invalid
signature"

**Comment by kroitor** [comment]
@presence35 what's your version of PHP ?

**Comment by presence35** [comment]
It was 7.2.  I tried 7.3 and same error

**Comment by presence35** [comment]
If this helps...

[image: image.png]

**Comment by kroitor** [comment]
> If this helps...
> [image: image.png]

Unfortunately, when you reply over email (not on GitHub) I don't receive those email attachments.

I'm testing with 7.3.2 and it works fine... 

This is very strange, though. It should work on your side as well, if it works for at least two other devs and if your actual version is up to date (same as on our side).

How do you install and upgrade CCXT, btw?

Also, is it hard fo you to try recreating the key to see if it makes any difference?

**Comment by presence35** [comment]
Created a new API..."invalid signature"

I just download the ZIP from github and extract it on my webhost. I do
nothing else. Bittrex fetchorders work fine.

Maybe I can give you my API key to test? I can make one that's read only.

**Comment by kroitor** [comment]
> Maybe I can give you my API key to test? I can make one that's read only.

If you can, please send it to igor@ccxt.trade, i'll try that on my side.

**Comment by frosty00** [comment]
@presence35 what code are you running in php that produces that error?

**Comment by presence35** [comment]
$order = $exchange->fetchOrder($orderID,$o['symbol'],($o['side']));

**Comment by kroitor** [comment]
@presence35 i've replied to you over email with a working example, let us know if you have further difficulties with it.
