### ISSUE TITLE
Bitfinex fetchClosedOrders does not return cancelled orders

### ISSUE THREAD

**Issue by FlickerBean** [ccxt/ccxt#5288]
This means that partially filled and then cancelled orders do not get accounted for in code.

Is this a bug, a Bitfinex issue or is this expected behaviour?

Is there a workaround?

**Comment by kroitor** [comment]
Hi!

Can you please post your verbose response and verbose request? You're using PHP, right?

```PHP
$id = 'bitfinex';

// instantiate the exchange by id
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));

// load all markets from the exchange
$markets = $exchange->load_markets ();

$exchange->verbose = true; // ←------------------ ADD THIS after load_markets ()

$orders = $exchange->fetch_closed_orders ();
```

↑ It will print a ton of info, can you copy-paste it here (without your keys, of course).

**Comment by FlickerBean** [comment]
Sure thing:

Request:
Array
(
    [0] => POST
    [1] => https://api.bitfinex.com/v1/orders/hist
    [2] => Array
        (
            [0] => X-BFX-APIKEY: xxx
            [1] => X-BFX-PAYLOAD: xxx=
            [2] => X-BFX-SIGNATURE: xxx
        )

    [3] => {"nonce":"1560422545037","request":"\/v1\/orders\/hist"}
)

Response:
Array
(
    [0] => POST
    [1] => https://api.bitfinex.com/v1/orders/hist
    [2] => 200
    [3] => 
    [4] => Array
        (
            [date] => Array
                (
                    [0] => Thu, 13 Jun 2019 10:42:19 GMT
                )

            [content-type] => Array
                (
                    [0] => application/json; charset=utf-8
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [set-cookie] => Array
                (
                    [0] => __cfduid=xxx; expires=Fri, 12-Jun-20 10:42:19 GMT; path=/; domain=.bitfinex.com; HttpOnly
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [etag] => Array
                (
                    [0] => W/"xxx"
                )

            [cache-control] => Array
                (
                    [0] => max-age=0, private, must-revalidate
                )

            [x-request-id] => Array
                (
                    [0] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                )

            [x-runtime] => Array
                (
                    [0] => 0.041054
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000
                )

            [x-download-options] => Array
                (
                    [0] => noopen
                )

            [x-permitted-cross-domain-policies] => Array
                (
                    [0] => none
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [expect-ct] => Array
                (
                    [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                )

            [server] => Array
                (
                    [0] => cloudflare
                )

            [cf-ray] => Array
                (
                    [0] => 4e637508dba16a41-LHR
                )

        )

    [5] => [{"id":26592623014,"cid":31735234657,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40667","avg_execution_price":"0.40667","side":"sell","type":"limit","timestamp":"1560329335.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"48.87585532","remaining_amount":"0.0","executed_amount":"48.87585532","src":"web"},{"id":26609210821,"cid":1560358836642,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40254","avg_execution_price":"0.40254","side":"sell","type":"limit","timestamp":"1560358837.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":26609203346,"cid":1560358823086,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40239","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560358823.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26592622946,"cid":31735133243,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4","avg_execution_price":"0.4","side":"sell","type":"limit","timestamp":"1560329335.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"24.43792766","remaining_amount":"0.0","executed_amount":"24.43792766","src":"web"},{"id":26591947510,"cid":1560328101585,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.39441","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560328102.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26591944135,"cid":1560328094589,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.3944","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560328095.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26591932542,"cid":1560328070247,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.3944","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560328070.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26591926651,"cid":1560328058202,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.3944","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560328058.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26591805313,"cid":30235935237,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44444","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"20.0","remaining_amount":"20.0","executed_amount":"0.0","src":"web"},{"id":26591805261,"cid":30235832491,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"20.0","remaining_amount":"20.0","executed_amount":"0.0","src":"web"},{"id":26591805471,"cid":30236221787,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.45778","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"77.79604093","remaining_amount":"77.79604093","executed_amount":"0.0","src":"web"},{"id":26591805392,"cid":30236105664,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.45333","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"38.89802046","remaining_amount":"38.89802046","executed_amount":"0.0","src":"web"},{"id":26591805351,"cid":30236020566,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44889","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"20.0","remaining_amount":"20.0","executed_amount":"0.0","src":"web"},{"id":26591805581,"cid":30236435322,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.46667","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"311.18416375","remaining_amount":"311.18416375","executed_amount":"0.0","src":"web"},{"id":26591805546,"cid":30236337651,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.46222","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327836.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"155.59208187","remaining_amount":"155.59208187","executed_amount":"0.0","src":"web"},{"id":26591805660,"cid":30236535820,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.47111","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327837.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"622.36832751","remaining_amount":"622.36832751","executed_amount":"0.0","src":"web"},{"id":26591805703,"cid":30236668556,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.47556","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327837.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1244.73665503","remaining_amount":"1244.73665503","executed_amount":"0.0","src":"web"},{"id":26591805798,"cid":30236795685,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.48","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560327837.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2489.4247104","remaining_amount":"2489.4247104","executed_amount":"0.0","src":"web"},{"id":26505933232,"cid":1560171073017,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.46601","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560171073.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"4606.1145","remaining_amount":"4606.1145","executed_amount":"0.0","src":"web"},{"id":26505903868,"cid":1560171029200,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44444","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560171029.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26505889635,"cid":1560171006047,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4342","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560171006.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26505879799,"cid":1560170988850,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.41573","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560170989.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26505868242,"cid":1560170969930,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40854","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560170970.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2000.0","remaining_amount":"2000.0","executed_amount":"0.0","src":"web"},{"id":26590231851,"cid":1560325056725,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.39502","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1560325057.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26557059764,"cid":1560266717910,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.38741","avg_execution_price":"0.38741","side":"sell","type":"limit","timestamp":"1560266718.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"897.21000002","executed_amount":"4102.78999998","src":"web"},{"id":26544728029,"cid":32935463667,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.39636","side":"buy","type":"market","timestamp":"1560244135.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"6000.0","remaining_amount":"0.0","executed_amount":"6000.0","src":"web"},{"id":26544303143,"cid":1560243187158,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.39495","avg_execution_price":"0.39495","side":"buy","type":"exchange limit","timestamp":"1560243187.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"63.31251667","remaining_amount":"0.0","executed_amount":"63.31251667","src":"web"},{"id":26505751960,"cid":1560170782058,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.39783","avg_execution_price":"0.39783","side":"sell","type":"limit","timestamp":"1560170782.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"6000.0","remaining_amount":"0.0","executed_amount":"6000.0","src":"web"},{"id":26240517829,"cid":1559685646158,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.379","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559685646.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"17000.0","remaining_amount":"17000.0","executed_amount":"0.0","src":"web"},{"id":26256301137,"cid":19760978180,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.40235188","side":"sell","type":"market","timestamp":"1559712561.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":26240630226,"cid":1559685779979,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.38816","avg_execution_price":"0.38816","side":"buy","type":"limit","timestamp":"1559685780.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":26234544914,"cid":1559676588919,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.3989","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1559676589.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"17000.0","remaining_amount":"17000.0","executed_amount":"0.0","src":"web"},{"id":26236917017,"cid":73676342584,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.39333359","side":"sell","type":"market","timestamp":"1559680076.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"17000.0","remaining_amount":"0.0","executed_amount":"17000.0","src":"web"},{"id":26234238705,"cid":1559676186476,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.39105","avg_execution_price":"0.39091489","side":"buy","type":"limit","timestamp":"1559676186.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"17000.0","remaining_amount":"0.0","executed_amount":"17000.0","src":"web"},{"id":26233708158,"cid":69120696436,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.39184784","side":"buy","type":"market","timestamp":"1559675521.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"29286.70282648","remaining_amount":"0.0","executed_amount":"29286.70282648","src":"web"},{"id":26191388924,"cid":1559606649964,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40554","avg_execution_price":"0.40593981","side":"sell","type":"market","timestamp":"1559606650.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"29830.699","remaining_amount":"543.99617352","executed_amount":"29286.70282648","src":"web"},{"id":26191374013,"cid":232621434,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.40487569","side":"sell","type":"market","timestamp":"1559606633.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"28000.0","remaining_amount":"0.0","executed_amount":"28000.0","src":"web"},{"id":26191125694,"cid":1559606329096,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.427","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1559606329.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"51956.4068","remaining_amount":"51956.4068","executed_amount":"0.0","src":"web"},{"id":26191282640,"cid":1559606523645,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40525","avg_execution_price":"0.4053","side":"buy","type":"market","timestamp":"1559606524.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"8000.0","remaining_amount":"0.0","executed_amount":"8000.0","src":"web"},{"id":26191035559,"cid":1559606202565,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42014","avg_execution_price":"0.42118107","side":"buy","type":"market","timestamp":"1559606203.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"20000.0","remaining_amount":"0.0","executed_amount":"20000.0","src":"web"},{"id":26190919996,"cid":86042895361,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42115241","side":"buy","type":"market","timestamp":"1559606043.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"28000.0","remaining_amount":"0.0","executed_amount":"28000.0","src":"web"},{"id":26172591585,"cid":1559574098867,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43509","avg_execution_price":"0.43404163","side":"sell","type":"market","timestamp":"1559574099.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"28000.0","remaining_amount":"0.0","executed_amount":"28000.0","src":"web"},{"id":26162554248,"cid":35264425138,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.44089711","side":"sell","type":"market","timestamp":"1559555264.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"14999.9999962","remaining_amount":"0.0","executed_amount":"14999.9999962","src":"web"},{"id":26125409761,"cid":1559484502106,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43889","avg_execution_price":"0.43899","side":"buy","type":"market","timestamp":"1559484502.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2333.33333","remaining_amount":"0.0","executed_amount":"2333.33333","src":"web"},{"id":26004072331,"cid":1559254982567,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.375","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559254983.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26047217609,"cid":1559329824108,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4258","avg_execution_price":"0.42663702","side":"sell","type":"market","timestamp":"1559329824.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"6472.4617583","remaining_amount":"0.0","executed_amount":"6472.4617583","src":"web"},{"id":26047108242,"cid":1559329622250,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42943","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1559329622.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"6472.4617583","remaining_amount":"6472.4617583","executed_amount":"0.0","src":"web"},{"id":26004050416,"cid":1559254954394,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.36","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559254954.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26004014344,"cid":1559254904917,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.37","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559254905.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"5000.0","executed_amount":"0.0","src":"web"},{"id":26003850357,"cid":1559254679565,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.38","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559254680.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"3333.0","remaining_amount":"3333.0","executed_amount":"0.0","src":"web"},{"id":26003713302,"cid":1559254498672,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.419","avg_execution_price":"0.41881482","side":"sell","type":"exchange market","timestamp":"1559254499.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2980.357518","remaining_amount":"0.0","executed_amount":"2980.357518","src":"web"},{"id":26002343597,"cid":1559252696052,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4117","avg_execution_price":"0.41181","side":"sell","type":"exchange market","timestamp":"1559252696.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1156.886608","remaining_amount":"0.0","executed_amount":"1156.886608","src":"web"},{"id":26001388661,"cid":1559251621653,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.40896","avg_execution_price":"0.40775","side":"buy","type":"market","timestamp":"1559251622.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"8230.8335","remaining_amount":"84.0906755","executed_amount":"8146.7428245","src":"web"},{"id":25977028385,"cid":1559210001271,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4455","avg_execution_price":"0.4455","side":"buy","type":"limit","timestamp":"1559210001.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"10992.3856","remaining_amount":"0.0","executed_amount":"10992.3856","src":"web"},{"id":25976995773,"cid":1559209938053,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4455","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559209938.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"21992.3856","remaining_amount":"21992.3856","executed_amount":"0.0","src":"web"},{"id":25972670453,"cid":27940973471,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.46862","side":"buy","type":"market","timestamp":"1559202341.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"0.12377576","remaining_amount":"0.0","executed_amount":"0.12377576","src":"web"},{"id":25943579509,"cid":1559151135850,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4533","avg_execution_price":"0.45359191","side":"buy","type":"stop","timestamp":"1559151136.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"21863.0","remaining_amount":"0.0","executed_amount":"21863.0","src":"web"},{"id":25940102612,"cid":1559145147285,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44947","avg_execution_price":"0.44884367","side":"sell","type":"market","timestamp":"1559145147.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"23626.7852","remaining_amount":"1763.66142424","executed_amount":"21863.12377576","src":"web"},{"id":25930962460,"cid":1559128923094,"cid_date":null,"gid":null,"symbol":"xlmusd","exchange":null,"price":"0.13703","avg_execution_price":"0.13703","side":"sell","type":"exchange market","timestamp":"1559128923.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1497.0","remaining_amount":"0.0","executed_amount":"1497.0","src":"web"},{"id":25930911164,"cid":40821869772,"cid_date":null,"gid":null,"symbol":"xmrusd","exchange":null,"price":null,"avg_execution_price":"94.1455559","side":"sell","type":"market","timestamp":"1559128822.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5.0","remaining_amount":"0.0","executed_amount":"5.0","src":"web"},{"id":25930909540,"cid":40818225995,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.44151749","side":"sell","type":"market","timestamp":"1559128818.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":25921943739,"cid":1559111989880,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42877","avg_execution_price":"0.42855","side":"buy","type":"market","timestamp":"1559111990.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1000.0","remaining_amount":"0.0","executed_amount":"1000.0","src":"web"},{"id":25919024841,"cid":1559107293330,"cid_date":null,"gid":null,"symbol":"xmrusd","exchange":null,"price":"91.608","avg_execution_price":"91.608","side":"buy","type":"market","timestamp":"1559107293.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1.0","remaining_amount":"0.0","executed_amount":"1.0","src":"web"},{"id":25919011853,"cid":1559107271123,"cid_date":null,"gid":null,"symbol":"xmrusd","exchange":null,"price":"91.608","avg_execution_price":"91.608","side":"buy","type":"market","timestamp":"1559107271.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2.0","remaining_amount":"0.0","executed_amount":"2.0","src":"web"},{"id":25918983130,"cid":1559107217881,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43184","avg_execution_price":"0.43184","side":"buy","type":"market","timestamp":"1559107218.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2000.0","remaining_amount":"0.0","executed_amount":"2000.0","src":"web"},{"id":25903798100,"cid":1559078037404,"cid_date":null,"gid":null,"symbol":"xmrusd","exchange":null,"price":"95.854","avg_execution_price":"95.854","side":"buy","type":"market","timestamp":"1559078037.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2.0","remaining_amount":"0.0","executed_amount":"2.0","src":"web"},{"id":25901263657,"cid":1559073245637,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44687","avg_execution_price":"0.44686","side":"buy","type":"market","timestamp":"1559073246.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2000.0","remaining_amount":"0.0","executed_amount":"2000.0","src":"web"},{"id":25892799854,"cid":1559059553407,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4235","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559059553.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"49075.8128","remaining_amount":"49075.8128","executed_amount":"0.0","src":"web"},{"id":25901021661,"cid":71248046750,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.44541537","side":"buy","type":"market","timestamp":"1559072848.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"22377.0078675","remaining_amount":"0.0","executed_amount":"22377.0078675","src":"web"},{"id":25892793571,"cid":1559059541257,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.423","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559059541.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"49075.8128","remaining_amount":"49075.8128","executed_amount":"0.0","src":"web"},{"id":25892738304,"cid":1559059445545,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4255","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1559059446.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"22377.0","remaining_amount":"22377.0","executed_amount":"0.0","src":"web"},{"id":25892680268,"cid":1559059348095,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4428","avg_execution_price":"0.44151518","side":"sell","type":"market","timestamp":"1559059348.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"23118.4602","remaining_amount":"741.4523325","executed_amount":"22377.0078675","src":"web"},{"id":25878011277,"cid":1559030130025,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4333","avg_execution_price":"0.0","side":"sell","type":"limit","timestamp":"1559030130.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"10000.0","remaining_amount":"10000.0","executed_amount":"0.0","src":"web"},{"id":25878303298,"cid":29096696467,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42802005","side":"sell","type":"market","timestamp":"1559030697.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"10000.0","remaining_amount":"0.0","executed_amount":"10000.0","src":"web"},{"id":25877037544,"cid":1559028489120,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42568","avg_execution_price":"0.42568","side":"buy","type":"market","timestamp":"1559028489.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"10000.0","remaining_amount":"0.0","executed_amount":"10000.0","src":"web"},{"id":25855405927,"cid":75357646899,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42416668","side":"buy","type":"market","timestamp":"1558990558.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"20900.17836273","remaining_amount":"0.0","executed_amount":"20900.17836273","src":"web"},{"id":25855203347,"cid":1558990247015,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42379","avg_execution_price":"0.42408494","side":"sell","type":"market","timestamp":"1558990247.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"24586.5415","remaining_amount":"3686.36313727","executed_amount":"20900.17836273","src":"web"},{"id":25854071553,"cid":73155960470,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42674386","side":"buy","type":"market","timestamp":"1558988356.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"21732.35019125","remaining_amount":"0.0","executed_amount":"21732.35019125","src":"web"},{"id":25853860350,"cid":1558988020516,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.4244","avg_execution_price":"0.42509285","side":"sell","type":"market","timestamp":"1558988021.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"25129.9294","remaining_amount":"3397.57920875","executed_amount":"21732.35019125","src":"web"},{"id":25853769068,"cid":72692038110,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42550465","side":"buy","type":"market","timestamp":"1558987892.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"25645.72392394","remaining_amount":"0.0","executed_amount":"25645.72392394","src":"web"},{"id":25853748946,"cid":1558987864606,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42438","avg_execution_price":"0.42449484","side":"sell","type":"market","timestamp":"1558987865.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"25667.8974","remaining_amount":"22.17347606","executed_amount":"25645.72392394","src":"web"},{"id":25853745559,"cid":72659980602,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.424322","side":"sell","type":"market","timestamp":"1558987860.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"15000.0","remaining_amount":"0.0","executed_amount":"15000.0","src":"web"},{"id":25851446374,"cid":1558984118747,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42963","avg_execution_price":"0.4295557","side":"buy","type":"market","timestamp":"1558984119.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"15000.0","remaining_amount":"0.0","executed_amount":"15000.0","src":"web"},{"id":25849945560,"cid":66646301451,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42142418","side":"sell","type":"market","timestamp":"1558981846.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"13600.8216595","remaining_amount":"0.0","executed_amount":"13600.8216595","src":"web"},{"id":25849673440,"cid":1558981440109,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42209","avg_execution_price":"0.42144597","side":"sell","type":"market","timestamp":"1558981440.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":25849309759,"cid":1558980865161,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.41987","avg_execution_price":"0.42029953","side":"sell","type":"market","timestamp":"1558980865.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":25847318638,"cid":1558977959279,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42083","avg_execution_price":"0.42142466","side":"buy","type":"market","timestamp":"1558977959.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"15651.1117","remaining_amount":"3030.4805688","executed_amount":"12620.6311312","src":"web"},{"id":25846125761,"cid":1558976264814,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42006","avg_execution_price":"0.4185868","side":"sell","type":"market","timestamp":"1558976265.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"10000.0","remaining_amount":"0.0","executed_amount":"10000.0","src":"web"},{"id":25845379106,"cid":1558975340224,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42818","avg_execution_price":"0.42803","side":"buy","type":"market","timestamp":"1558975340.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2500.0","remaining_amount":"0.0","executed_amount":"2500.0","src":"web"},{"id":25845314899,"cid":1558975261642,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43645","avg_execution_price":"0.4352","side":"buy","type":"market","timestamp":"1558975262.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2500.0","remaining_amount":"0.0","executed_amount":"2500.0","src":"web"},{"id":25845284013,"cid":1558975224001,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43832","avg_execution_price":"0.43752243","side":"buy","type":"market","timestamp":"1558975224.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2500.0","remaining_amount":"0.0","executed_amount":"2500.0","src":"web"},{"id":25844929806,"cid":1558974720234,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44479","avg_execution_price":"0.44434","side":"sell","type":"market","timestamp":"1558974720.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":25844868700,"cid":1558974627413,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44306","avg_execution_price":"0.44391","side":"sell","type":"market","timestamp":"1558974627.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"1159.0","remaining_amount":"0.0","executed_amount":"1159.0","src":"web"},{"id":25844787831,"cid":1558974506084,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.44154","avg_execution_price":"0.44160961","side":"sell","type":"market","timestamp":"1558974506.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"5000.0","remaining_amount":"0.0","executed_amount":"5000.0","src":"web"},{"id":25844036562,"cid":1558973428284,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.43015","avg_execution_price":"0.43092089","side":"buy","type":"market","timestamp":"1558973428.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"14000.0","remaining_amount":"1324.9965717","executed_amount":"12675.0034283","src":"web"},{"id":25842648874,"cid":1558971304879,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.422","avg_execution_price":"0.0","side":"buy","type":"limit","timestamp":"1558971305.0","is_live":false,"is_cancelled":true,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"15510.7731","remaining_amount":"15510.7731","executed_amount":"0.0","src":"web"},{"id":25842662790,"cid":1558971328148,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42366","avg_execution_price":"0.42402159","side":"buy","type":"market","timestamp":"1558971328.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"11964.1871","remaining_amount":"0.0","executed_amount":"11964.1871","src":"web"},{"id":25842657918,"cid":56119789366,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":null,"avg_execution_price":"0.42333828","side":"sell","type":"market","timestamp":"1558971320.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"12000.03533367","remaining_amount":"0.0","executed_amount":"12000.03533367","src":"web"},{"id":25842458642,"cid":1558970969171,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.42646","avg_execution_price":"0.42556711","side":"sell","type":"market","timestamp":"1558970969.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"2812.0","remaining_amount":"0.0","executed_amount":"2812.0","src":"web"},{"id":25837267426,"cid":1558962122169,"cid_date":null,"gid":null,"symbol":"xrpusd","exchange":null,"price":"0.41832","avg_execution_price":"0.41800774","side":"sell","type":"market","timestamp":"1558962122.0","is_live":false,"is_cancelled":false,"is_hidden":0,"oco_order":0,"was_forced":false,"original_amount":"8000.0","remaining_amount":"0.0","executed_amount":"8000.0","src":"web"}]
)

**Comment by FlickerBean** [comment]
Why was this closed?

**Comment by kroitor** [comment]
> Why was this closed?

Because it was fixed in the most recent version 1.18.685+ eight hours ago )
If you update to the most recent version – it should work fine (let us know if not).
We will be happy if you report back whether the fix resolved the issue for you or not.

**Comment by FlickerBean** [comment]
I'm such a fool, I missed the commit reference in the closed message! Sorry.

**Comment by FlickerBean** [comment]
Something is still not right. fetchClosedOrders() is now returning only two orders. One with a key of 'canceled' and one with a key of 'closed'.

We have:
```
array(2) {
  ["canceled"]=>
  array(15) {
    ["info"]=>
    array(20) {
      ["id"]=>
      int(26692225344)
      ...
 ["fee"]=>
    NULL
  }
  ["closed"]=>
  array(15) {
    ["info"]=>
    array(20) {
      ["id"]=>
      ....
  }
}
```

**Comment by kroitor** [comment]
@FlickerBean let me check it again and I will get back to you shortly. Pardon for the inconvenience.

**Comment by kroitor** [comment]
@FlickerBean ok, i found one more issue there, fixed it, and it should work fine in 1.18.702. Let us know if you have difficulties with it after updating once again. Thx again for your feedback!
