### ISSUE TITLE
Python bitstamp create_order

### ISSUE THREAD

**Issue by matthijsb** [ccxt/ccxt#540]
When i try to create an order on bitstamp using the python client, it raises an error:
{"error": "Missing key, signature and nonce parameters"}
(while keys are provided, other calls like fetch_balance work fine)

It seems to be something similar to the this:
https://github.com/maxme/bitcoin-arbitrage/issues/22

**Comment by kroitor** [comment]
@matthijsb hi! Thanks for your report! Will take a look and add a fix to it, hopefully, soon.

**Comment by kroitor** [comment]
@matthijsb can you please post the full verbose output of it?

**Comment by matthijsb** [comment]
Here you go:

('https://www.bitstamp.net/api/buy', 'POST', 'https://www.bitstamp.net/api/buy', '\nRequest:', {'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'ccxt/1.10.63 (+https://github.com/ccxt-dev/ccxt) Python/2.7.13'}, 'nonce=XXX&amount=0.01&key=XXX&signature=XXX&price=5500&id=btcusd')
('POST', 'https://www.bitstamp.net/api/buy', '\nResponse:', 'Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, accept, cache-control\r\nAccess-Control-Allow-Methods: POST, GET\r\nAccess-Control-Allow-Origin: *\r\nCache-Control: max-age=0\r\nContent-Language: en\r\nContent-Type: application/json\r\nDate: Sun, 12 Nov 2017 20:03:00 GMT\r\nExpires: Sun, 12 Nov 2017 20:03:00 GMT\r\nLast-Modified: Sun, 12 Nov 2017 20:03:00 GMT\r\nServer: Apache\r\nStrict-Transport-Security: max-age=63072000; includeSubDomains\r\nVary: Accept-Language\r\nX-Frame-Options: SAMEORIGIN\r\ntransfer-encoding: chunked\r\nConnection: Close\r\nSet-Cookie: nlbi_99025=9jLMRrj5x0fy9Um48F1n9AAAAAD6cZrGuHn3qlP6Krqlwuo+; path=/; Domain=.bitstamp.net\r\nSet-Cookie: visid_incap_99025=fLQj2xatTD6zZw3o1TWzgvSoCFoAAAAAQUIPAAAAAADBUZrRQ28gu2xhHtvkPtEV; expires=Mon, 12 Nov 2018 14:47:45 GMT; path=/; Domain=.bitstamp.net\r\nSet-Cookie: incap_ses_764_99025=UWp4W7ItWSsek7JbFEaaCvSoCFoAAAAA5OUeTRSOroPJoqW0ILfg/g==; path=/; Domain=.bitstamp.net\r\nSet-Cookie: ___utmvmDSumyLc=SkmEIYfmOEB; path=/; Max-Age=900\r\nSet-Cookie: ___utmvaDSumyLc=Zlj\x01shpA; path=/; Max-Age=900\r\nSet-Cookie: ___utmvbDSumyLc=HZV\r\n    XDlOZale: WtG; path=/; Max-Age=900\r\nX-Iinfo: 14-38204879-38203843 2NNN RT(1510516980183 37) q(0 0 0 6) r(0 0)\r\nX-CDN: Incapsula\r\nContent-Encoding: gzip\r\n', u'{"error": "Missing key, signature and nonce parameters"}')
Traceback (most recent call last):
  File "test-bitstamp.py", line 31, in <module>
    bitstamp.create_order('BTC/USD', 'limit', 'buy', '0.01', '5500')
  File "/home/dev/trader/ccxt/bitstamp1.py", line 170, in create_order
    'id': response['id'],
KeyError: 'id'

And this is the accompanying code:

import ccxt

bitstamp = ccxt.bitstamp1({
    "apiKey": "XXX",
    "secret": "XXX",
    "verbose": True,
    "uid": "XXX",
})

bitstamp.create_order('BTC/USD', 'limit', 'buy', '0.01', '5500')

**Comment by kroitor** [comment]
@matthijsb does fetch_balance work for you?

**Comment by kroitor** [comment]
This issue should be fixed as of 1.10.77. Let us know if you still have difficulties with it. Thx for reporting!

**Comment by matthijsb** [comment]
Igor Kroitor schreef op 2017-11-12 21:17:

> @matthijsb [1] does fetch_balance work for you? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

Hi Igor, i tried the new version, but unfortunatly it still doesnt work
for me (it throws the same error). 
fetch_balance (and other functions) work fine! 

Links:
------
[1] https://github.com/matthijsb
[2] https://github.com/ccxt/ccxt/issues/540#issuecomment-343764122
[3]

**Comment by kroitor** [comment]
@matthijsb hi, can you please repost the verbose output with the new version? I'll be able to debug it then, thx! My bitstamp account is still under verification, unfortunately.

**Comment by kroitor** [comment]
@matthijsb also, can you please try the same code with bitstamp v2? 

```Python
import ccxt

bitstamp = ccxt.bitstamp({  # bitstamp without the "1"
    "apiKey": "XXX",
    "secret": "XXX",
    "verbose": True,
    "uid": "XXX",
})

bitstamp.create_order('BTC/USD', 'limit', 'buy', '0.01', '5500')
```

Does it also fail to open the order for you with v2?

**Comment by matthijsb** [comment]
Igor Kroitor schreef op 2017-11-12 23:10:

> @matthijsb [1] also, can you please try the same code with bitstamp v2?
> 
> import ccxt
> 
> bitstamp = ccxt.bitstamp({  # bitstamp without the "1"
> "apiKey": "XXX",
> "secret": "XXX",
> "verbose": True,
> "uid": "XXX",
> })
> 
> bitstamp.create_order('BTC/USD', 'limit', 'buy', '0.01', '5500')
> 
> Does it also fail to open the order for you with v2? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

Good catch! I left v1 there to test (nobody wants to use that one i
guess ;-), with v2 it works as expected! 

Links:
------
[1] https://github.com/matthijsb
[2] https://github.com/ccxt/ccxt/issues/540#issuecomment-343772240
[3]
