### ISSUE TITLE
Error creating order to exmo - Price rounded up to 1

### ISSUE THREAD

**Issue by rubobaquero** [ccxt/ccxt#545]
I am trying to create an order on exmo:

```
$exchange = new \ccxt\exmo([XXX]);
$exchange->verbose = true;
$exchange->load_markets();

$volume = 20;
$price = 0.00003200;
$order = $exchange->create_order("XRP/BTC", "limit", "buy", $volume, $price);
```

The problem is that the price is being rounded up to 1 as the request shows:

```
Array
(
    [0] => POST
    [1] => https://api.exmo.com/v1/order_create
    [2] => Array
        (
            [0] => Content-Type: application/x-www-form-urlencoded
            [1] => Key: XXXXXXX
            [2] => Sign: XXXXXXX
            [User-Agent] => ccxt/1.9.282 (+https://github.com/ccxt-dev/ccxt) PHP/7.0.14
        )

    [3] => nonce=1510502461&pair=XRP_BTC&quantity=20&price=1&type=buy
)
```

I am running version 1.18.68 (latest downloaded by composer, didn't know why it isn't available 1.18.71. I have tried with "ccxt/ccxt": "dev-master" and "ccxt/ccxt": "*" and it didn't find anything new)

**Comment by kroitor** [comment]
This was fixed in 1.10.72+. Thx for reporting!

**Comment by rubobaquero** [comment]
kroitor, still having the same issue with version 1.10.73.

As you can see, price in POST var is 1 and i set it to 0.00003200:

```
$price = 0.00003200;
$order = $exchange->create_order("XRP/BTC", "limit", "buy", $volume, $price);
```

`[3] => nonce=1510502461&pair=XRP_BTC&quantity=20&**price=1**&type=buy`

**Comment by kroitor** [comment]
@rubobaquero sorry, let me double-check that...

**Comment by kroitor** [comment]
@rubobaquero can you please verify that your installed version actually has the same code in exmo.php ?

https://github.com/ccxt/ccxt/blob/1.10.73/php/exmo.php

<img width="863" alt="screen shot 2017-11-12 at 20 40 49" src="https://user-images.githubusercontent.com/1294454/32701608-e6224012-c7e9-11e7-8ed4-cdd2aada5b6b.png">

https://github.com/ccxt/ccxt/issues/546#issuecomment-343753664
