### ISSUE TITLE
Authorization fails for LakeBTC when calling private API

### ISSUE THREAD

**Issue by petercollingridge** [ccxt/ccxt#547]
When trying to call `fetch_balance()` for with lakeBTC I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lakebtc.py", line 72, in fetch_balance
    response = self.privatePostGetAccountInfo()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lakebtc.py", line 199, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 258, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lakebtc.py", line 193, in sign
    'Authorization': "Basic " + self.apiKey + ':' + signature,
TypeError: must be str, not bytes
```

https://github.com/ccxt/ccxt/blob/4535a1d7fbae1a55c036bacba799cdcdc4deb51f/python/ccxt/lakebtc.py#L193

I think this is because both `self.apiKey` and `signature` are bytes and you are trying to concatenate them into a string. I think they need to be converted into strings. I think also, you need to create the string `self.apiKey + ':' + signature` and convert that into base64 before adding it 'Basic '.

**Comment by kroitor** [comment]
@petercollingridge thx for reporting this, will fix right away!

**Comment by kroitor** [comment]
@petercollingridge this is fixed in 1.10.74+. Thx again!

**Comment by kroitor** [comment]
Ok, this is now fixed completely, let us know if you have any difficulties with it. Thx again!

**Comment by LaurentIsRunning** [comment]
Hi, 
@kroitor  I've got the last version 1.10.914 from pip install and I still have the same issue (i'm working in async).

Here is the error message:
`2018-01-31 11:21:18,343 - ERROR - message
Traceback (most recent call last):
   File "env\lib\site-packages\ccxt\async\lakebtc.py", line 84, in fetch_balance
    response = await self.privatePostGetAccountInfo()
  File "env\lib\site-packages\ccxt\async\lakebtc.py", line 216, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "env\lib\site-packages\ccxt\async\base\exchange.py", line 88, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "env\lib\site-packages\ccxt\async\base\exchange.py", line 109, in fetch
    async with session_method(url, data=encoded_body, headers=headers, timeout=(self.timeout / 1000), proxy=self.aiohttp_proxy) as response:
  File "env\lib\site-packages\aiohttp\client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "env\lib\site-packages\aiohttp\client.py", line 275, in _request
    resp = req.send(conn)
  File "env\lib\site-packages\aiohttp\client_reqrep.py", line 463, in send
    writer.write_headers(status_line, self.headers)
  File "env\lib\site-packages\aiohttp\http_writer.py", line 247, in write_headers
    [k + SEP + v + END for k, v in headers.items()])
  File "env\lib\site-packages\aiohttp\http_writer.py", line 247, in <listcomp>
    [k + SEP + v + END for k, v in headers.items()])
TypeError: must be str, not int`

Thank you very much in advance, 
Laurent

**Comment by LaurentIsRunning** [comment]
OK I've changed lakebtc.py like this and it works now : 

`headers = {
                'Json-Rpc-Tonce': str(nonce),
                'Authorization': "Basic " + self.decode(base64.b64encode(auth)),
                'Content-Type': 'application/json',
            }`

**Comment by kroitor** [comment]
@LaurentIsRunning this is fixed in the most recent version of ccxt as well, thx for reporting!
