### ISSUE TITLE
Missing Status:Rejected

### ISSUE THREAD

**Issue by justsaid** [ccxt/ccxt#5831]
https://github.com/ccxt/ccxt/blob/b5e0eb37daad45a7259dc55ee8f99530eac88a1e/python/ccxt/lykke.py#L296

Hi,
The Status Rejected seems to be missing.
You can check all the valid status values here:
https://hft-api.lykke.com/swagger/ui/#!/Orders/GetOrders

thx & regards
Said

**Comment by kroitor** [comment]
Fixed in 1.18.1157. The new build will arrive in 15 minutes. Thx for reporting!

**Comment by justsaid** [comment]
Thx Kroitor 👍

**Comment by justsaid** [comment]
while calling lykke.fetch_closed_orders() or lykke.fetch_orders() I still don’t get the rejected orders.
I think 'Rejected' should be mapped to 'canceled' order 'closed' to be returned by fetch_orders() or fetch_closed_orders()

`'Rejected': 'canceled',`

I don’t know exactly how the mapping of status in ccxt works, what we need is just that the rejected orders are returned by lykke.fetch_closed_orders() or lykke.fetch_orders()

**Comment by kroitor** [comment]
@justsaid lykke endpoint for `fetchClosedOrders` can only take one status at a time, so, it will fetch `Matched`  (aka `closed`) orders by default. If you want to fetch the rejected orders, you can do that using `params` overrides as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
exchange.fetch_closed_orders(symbol, since, limit, { 'status': 'Rejected' })
```

Lmk if that does not help.
