### ISSUE TITLE
[Bittrex] Deposit address generation logic changed

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#8235]
- OS: All
- Programming Language version: Nodejx
- CCXT version: ccxt@1.40.26

In bittrex v1.1, if no deposit address has been created previously for requested symbol, it would be requested automatically after the "getaddress" call.

Now, in bittrex v3 GET "v3/addresses/symbol" just returns "404 Not Found" if no address has been created previously.
It should be handled with POST  "v3/addresses/symbol":
https://bittrex.github.io/api/v3#operation--addresses-post

node_modules/ccxt/js/bittrex.js (line 1196):
```
async fetchDepositAddress (code, params = {}) {
        await this.loadMarkets ();
        const currency = this.currency (code);
        const request = {
            'currencySymbol': currency['id'],
        };
        const response = await this.privateGetAddressesCurrencySymbol (this.extend (request, params));
        // {
        //     "status": "PROVISIONED",
        //     "currencySymbol": "BTC",
        //     "cryptoAddress": "1PhmYjnJPZH5NUwV8AUjqkeDkCBpbE2xqX"
        // }
        let address = this.safeString (response, 'cryptoAddress');
        const message = this.safeString (response, 'status');
        if (!address || message === 'REQUESTED') {
            throw new AddressPending (this.id + ' the address for ' + code + ' is being generated (pending, not ready yet, retry again later)');
        }
        let tag = undefined;
        if (currency['type'] in this.options['tag']) {
            tag = address;
            address = currency['address'];
        }
        this.checkAddress (address);
        return {
            'currency': code,
            'address': address,
            'tag': tag,
            'info': response,
        };
    }
```

```
bittrex GET https://api.bittrex.com/v3/addresses/symbol
404 Not Found
 {"code":"NOT_FOUND"}

```

**Comment by kroitor** [comment]
Fixed in 1.40.31. The new build will arrive in ~20 minutes. Thanks for reporting!

**Comment by krychla1** [comment]
Hi @kroitor,
sorry, I've been to busy to check it after your fix, I came across it now. We still have a problem on address request:
bittrex.js line 1252 (ccxt 1.41.48):

 bittrex GET https://api.bittrex.com/v3/addresses/SHR 404
Response:
 {
....
}
 {"code":"NOT_FOUND"}

I can see, that you created another function createDepositAddress for it, however, it throws error from line 1218 "unresolved function privatePostAddressesCurrencySymbol()".

I am not very familiar, how custom exchange functions are created and what the suffix "CurrencySymbol" does, however if removed, it seems to work.

Could you please have a look? 

Thank you.

**Comment by kroitor** [comment]
@krychla1 thx for pointing it out, looks like a leftover bug, i just pushed a fix, please, let me know if you have issues with it after upgrading to 1.41.50+ (the new build will arrive in ~20min)
