### ISSUE TITLE
Binance future API is opening 3 month contracts

### ISSUE THREAD

**Issue by beursdummy** [ccxt/ccxt#8386]
- OS: Ubuntu 16.4
- Programming Language version: Python
- CCXT version:

it seems defaulttype future is connecting to 3 month contracts

binance_futures = ccxt.binance({'apiKey': APIKey,'secret': APISecret,'enableRateLimit': True,'options': {'defaultType': 'future',},})

**Comment by Kalelv45** [comment]
same here, can't download historic data, there is just 1 candle. That I now understand is from the 3 months contract and no more from the perpetual future contract.

**Comment by beursdummy** [comment]
I connected to spot for now to feed my charts:

binance_futures = ccxt.binance({'apiKey': APIKey,'secret': APISecret,'enableRateLimit': True,'options': {'defaultType': 'spot',},})

I was lucky I saw it on time and the contract was in a very big profit but still I hope not many people will be affected

**Comment by Kalelv45** [comment]
It seems they are updating today, must have been an error from their part. I will opt for the same solution, for the moment. 
Luckily I was awake and on the terminal as well. Very irresponsabile.

**Comment by beursdummy** [comment]
Seems OK now! Tnx!

**Comment by beursdummy** [comment]
For now it seems only the high price in fetch_ohlcv is returning a bad number

**Comment by kroitor** [comment]
@beursdummy, @Kalelv45 do you have the most recent versions of CCXT? What are your version numbers?

**Comment by beursdummy** [comment]
Name: ccxt
Version: 1.30.24
Summary: A JavaScript / Python / PHP cryptocurrency trading library with support for 130+ exchanges
Home-page: https://ccxt.trade
Author: Igor Kroitor
Author-email: igor.kroitor@gmail.com
License: MIT
Location: /home/cryptocoinz/.local/lib/python3.5/site-packages
Requires: cryptography, requests, certifi, setuptools
Required-by:

**Comment by beursdummy** [comment]
Name: ccxt
Version: 1.30.24

**Comment by beursdummy** [comment]
upgraded to Version: 1.32.51 and still same issue

**Comment by kroitor** [comment]
@beursdummy your version is still too old, and it's a troubleshooting step 1 to upgrade to the most recent version, which is 1.41.50+. The exchanges are updating their APIs all the time, so you have to keep your software up to date.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Let me know if that does not help. Closing this for now, feel free to reopen it or just ask further questions if any.

**Comment by beursdummy** [comment]
I have been upgrading it wrong I think. I always perform

pip3 uninstall ccxt and then a pip3 install ccxt which doesn't give me the latest version apparently.

what is the best way to upgrade and maybe automatically?

**Comment by kroitor** [comment]
@beursdummy do you have more than one python installed in the system? Is it a MacOS? Always check your version in runtime (do not trust `pip list`). Paste your output after running `pip3 install ccxt --upgrade`:

```Python
import ccxt
print('CCXT version:', ccxt.__version__)
```

**Comment by Kalelv45** [comment]
I do not think it is CCXT version related. I updated and same error apply. Have you tried to fetch OHCLV on binance futures BTC/USDT contract, as right now, it gives me just 3 candles in the all history. It is like it is downloading a new contract that has just been listed. Pretty sure is an error from their front. 
let me know if you are able to fetch BTC/USDT futures contract in some way.

**Comment by kroitor** [comment]
@Kalelv45 binance had changed the mapping with symbols, therefore it is very well related:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {'defaultType': 'future'}
})

ohlcvs = exchange.fetch_ohlcv('BTC/USDT')
print('Fetched', len(ohlcvs), 'ohlcvs')
```

```
~/ccxt/python $ python3
Python 3.8.2 (default, Dec 21 2020, 15:06:03)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.41.51
>>> exchange = ccxt.binance({
...     'enableRateLimit': True,
...     'options': {'defaultType': 'future'}
... })
>>>
>>> ohlcvs = exchange.fetch_ohlcv('BTC/USDT')
>>> print('Fetched', len(ohlcvs), 'ohlcvs')
Fetched 500 ohlcvs
>>>
```

P.S. If you upgarde to version 1.41.53+, you will be able to fetch up to 1500 candles in one go.

**Comment by beursdummy** [comment]
so i have 2 bots running

one on 1.41.51 and one on the latest 1.41.53

when I both run ohlcv i get this for BTC

1.41.53
LOW: 18081.65
HIGH: 41662.12939

1.41.51
LOW: 36751.29632
HIGH: 38050.696749999996

**Comment by kroitor** [comment]
@beursdummy found a leftover bug there, pushed a fix for it, if you upgrade to 1.41.54 in ~20 minutes it should work fine (tested on my side).

**Comment by alitaheri** [comment]
This is probably because of how the binance module is handling pairs. Since binance futures has added quarterly future contracts ALONG perpetual contracts, we now have multiple pairs with the same BASE/QUOTE but with different delivery options.

BTCUSDT: [Perpetual BTC/USDT](https://www.binance.com/en/futures/BTCUSDT)
BTCUSDT_210326: [Quarterly BTC/USDT](https://www.binance.com/en/futures/btcusdt_quarter)

same with

BTCBUSD: https://www.binance.com/en/futures/BTC_BUSD
BTCBUSD_210226: not listed on their website yet

Since they resolve to the same BASE/QUOTE value they will conflict in the market mapping, and since the latter is newer, it wins. Hence the problem we are facing.

The fix is simple, make the mapping allow arbitrary ids. so instead of BTC/USDT we should have BTCUSDT and BTCUSDT_210326. use the id of the exchange instead of using a custom mapping.

**Comment by kroitor** [comment]
@alitaheri that's a different issue though, and it's already fixed in 1.41.53+.

**Comment by alitaheri** [comment]
@kroitor please take my comment  into account. The problem originally mentioned in this issue is still there.

**Comment by kroitor** [comment]
@alitaheri what's your version of CCXT?

**Comment by alitaheri** [comment]
wait, I might have forgotten to run `npm i` ^_^

**Comment by alitaheri** [comment]
wait hold on. it's fixed for BTCUSDT, but not for every pair. there is also a BTCBUSD variant.

**Comment by kroitor** [comment]
@alitaheri BTC/BUSD is a different pair though and it's there.

**Comment by kroitor** [comment]
@alitaheri 

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {'defaultType': 'future'},
})
exchange.load_markets()
for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['symbol'], market['id'])
```

**Comment by alitaheri** [comment]
btcbusd also has a perpetual contract and a quarterly future contract. BTCBUSD, BTCBUSD_210129, BTCBUSD_210226,

**Comment by kroitor** [comment]
@alitaheri we do not decide which markets to show, i don't see any quarterly BUSD futures here: https://fapi.binance.com/fapi/v1/exchangeInfo

**Comment by alitaheri** [comment]
ok, this is weird. these two will probably be added a little later. but binance is providing live data for them. O.o

Anyways, I see that it's working as intended. Thanks for putting your time into it to explain everything.

**Comment by beursdummy** [comment]
tnx guys for the great work and tnx @alitaheri for pointing me to the BTCBUSD contracts. I was waiting for thos and apparently already live for 14 days

**Comment by kroitor** [comment]
@alitaheri you can see those quarterly contracts on Binance testnet, but not on their production server yet:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {'defaultType': 'future'},
})
exchange.set_sandbox_mode(True)  # ←-------------------------------- add this before loading the markets
exchange.load_markets()
for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['symbol'], market['id'])
```

The testnet is a different endpoint though: https://testnet.binancefuture.com/fapi/v1/exchangeInfo

**Comment by alitaheri** [comment]
Yeah. Well, we are using a third party service, they list everything from testnet and mainnet. I wasn't aware of this a moment ago 😄
