### ISSUE TITLE
Can't make POST requests for Kucoin

### ISSUE THREAD

**Issue by marcusl33** [ccxt/ccxt#997]
Can't seem to make POST requests on Kucoin, it says that "Signature verification failed". All GET requests have worked fine so far. 

- OS: Mac OS
- Programming Language: Python (ipynb format)
- CCXT version: 1.10
- Exchange: Kucoin
- Method: create_order

```
ku_client.create_order('LTC/BTC', 'limit', 'buy', .01, 0.01655)



Result:
AuthenticationError: kucoin {"msg":"Signature verification failed","timestamp":1514554308458,"code":"UNAUTH","success":false}
```

**Comment by gaardiolor** [comment]
Ha, you just beat me with creating this issue by one minute. Same problem here using latest version ccxt-1.10.508

**Comment by marcusl33** [comment]
Hmm did you try playing around with the sign method? Let me know if you find some solution!

**Comment by kroitor** [comment]
For some reason I can't access them now from wherever I try...

<img width="706" alt="screen shot 2017-12-29 at 16 54 41" src="https://user-images.githubusercontent.com/1294454/34438603-084b2cd2-ecb9-11e7-8712-595d31dce4dd.png">

**Comment by gaardiolor** [comment]
Yeah, they're having load issues. Sometimes that page works, (it does for me at the moment).
Some more info when that page works:
```
import ccxt
import test_config as config
from pprint import pprint
import time

e = ccxt.kucoin()
e.apiKey = config.exchange_keys['kucoin']['key']
e.secret = config.exchange_keys['kucoin']['secret']
e.timeout = 60000
e.proxies = {'http': 'http://localhost:8080',
             'https': 'http://localhost:8080'}
balances = e.fetch_balance()
print(balances['ETH'])
time.sleep(1)
e.createLimitSellOrder('ETH/BTC', 0.00059940, 0.04978104)


C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/Carousel2/_test/test_kucoin.py
{'free': 0.0005994, 'used': 0.0, 'total': 0.0005994}
Traceback (most recent call last):
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 345, in fetch_requests
    response.raise_for_status()
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://api.kucoin.com/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Carousel2/_test/test_kucoin.py", line 15, in <module>
    e.createLimitSellOrder('ETH/BTC', 0.00059940, 0.04978104)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1050, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 298, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 471, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 290, in fetch2
    return self.fetch_requests(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 357, in fetch_requests
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 465, in handle_errors
    raise AuthenticationError(self.id + ' ' + self.json(response))
ccxt.base.errors.AuthenticationError: kucoin {"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1514555842503}
```

**Comment by kroitor** [comment]
@gaardiolor can you add the lines that are output upon sending the request? There should be an URL + headers (remove keys if necessary) + request body params...

**Comment by gaardiolor** [comment]
```
POST https://api.kucoin.com/v1/order 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514556151971', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL
```

**Comment by marcusl33** [comment]
@kroitor so what's the solution to this?

**Comment by kroitor** [comment]
@marcusl33, This is fixed in version 1.10.510 (will be available in 5 minutes, i was going to update you on availability). Please retry the same code with it in 5-10 minutes. We will be happy if you report back whether it works for you normally or not. Tested it on our side. Thx!

**Comment by kroitor** [comment]
Version 1.10.510 has arrived.

**Comment by gaardiolor** [comment]
unfortunately still an error; 
```
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Test2/_test/test_kucoin.py", line 16, in <module>
    e.createLimitSellOrder('ETH/BTC', 0.00059940, 0.04978104)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1050, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 301, in create_order
    'id': self.safe_string(response['data'], 'orderOid'),
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 474, in safe_string
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] else default_value
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kroitor** [comment]
@gaardiolor please, verbose output, starting from URL + headers + body ;)

**Comment by gaardiolor** [comment]
Yeah sorry, 
```
POST https://api.kucoin.com/v1/order?amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514560455632', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL
```

**Comment by gaardiolor** [comment]
my debugging proxy gets the following response:
```
{"success":false,"code":"ERROR","msg":"The precision of amount(ETH) is incorrect. The precision of ETH is 6","timestamp":1514560457260,"data":null}
```

**Comment by kroitor** [comment]
Oh, no... %))) When I say starting from, I don't mean only URL + headers + body, I mean all of it, starting from URL + headers + body up to the breaking point %) Never mind, no worries, I'll do it on my side )

**Comment by marcusl33** [comment]
hmm @gaardiolor are GET requests working for you?

**Comment by marcusl33** [comment]
they're working for me now thanks @kroitor !

**Comment by gaardiolor** [comment]
@marcusl33 yes get requests are working
@kroitor Hopefully my proxy message helps, full headers with snips:
```
GET https://api.kucoin.com/v1/market/open/symbols 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/symbols 
Response: {'Date': 'Fri, 29 Dec 2017 15:14:08 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>; Expires=Fri, 05 Jan 2018 15:14:06 GMT; Path=/, SESSION=<snip>; Path=/; HttpOnly', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '43713'} {"success":true,"code":"OK","msg":"Operation succeeded.",M<nip>
GET https://api.kucoin.com/v1/market/open/coins 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/coins 
Response: {'Date': 'Fri, 29 Dec 2017 15:14:13 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': '<snip>; Expires=Fri, 05 Jan 2018 15:14:10 GMT; Path=/, SESSION=<snip>; Path=/; HttpOnly', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '17325'} {"success":true,"code":"OK","msg":"Operation succeeded."<snip>
GET https://api.kucoin.com/v1/account/balance?limit=20&page=1 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514560452973', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/account/balance?limit=20&page=1 
Response: {'Date': 'Fri, 29 Dec 2017 15:14:15 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>+<snip>/<snip>; Expires=Fri, 05 Jan 2018 15:14:14 GMT; Path=/', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '6923'} {"success":true,"code":"OK","msg":"Operation succeeded.",<snip>
{'free': 0.0005994, 'used': 0.0, 'total': 0.0005994}
POST https://api.kucoin.com/v1/order?amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514560455632', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL
```

**Comment by kroitor** [comment]
@gaardiolor well, the problem consists of two parts:
1. There was a problem with detecting this error in Python and it is now fixed in the upcoming version 1.10.511. It will throw an InvalidOrder exception at you.
2. The amount you submit is 0.0005994. That is a precision of 7 decimal digits, whereas Kucoin wants 6. This aspect of precision should be handled in CCXT, but because of how Kucoin API is structured, some parts of the info about the precision does not get propagated where needed. Therefore it does limit your precision automatically and it goes through as number 0.0005994, whereas it should have been ETH 0.000599. This will be fixed in CCXT soon, and, in the meantime, I can offer a manual workaround to you, if you do the following before submitting your order:
```Python
amount = exchange.truncate (amount, 6)  # truncate (or round) the price to 6 decimals
order = exchange.create_order (...
```

**Comment by gaardiolor** [comment]
@kroitor ok, thanks! 
Just upgraded to version 511, but I still get TypeError: argument of type 'NoneType' is not iterable . I'll go ahead and collect debugging and snip things.

**Comment by kroitor** [comment]
@gaardiolor in order to debug it, I need to see their responses (your "proxy messages").

**Comment by gaardiolor** [comment]
Yeah it's the same, I didn't change precision yet with exchange.truncate, I'm just testing the exception. So I'm expecting an exception, but not TypeError , it should be InvalidOrder.

**Comment by gaardiolor** [comment]
ok, done snipping (would be really nice if you'd implement a debug option that leaves out things like sessions, cookies, fill json responses and API keys)

So this is just the error handling part, I'm getting the wrong exception when not using correct precision.
```
GET https://api.kucoin.com/v1/market/open/symbols 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/symbols 
Response: {'Date': 'Fri, 29 Dec 2017 15:40:45 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>; Expires=Fri, 05 Jan 2018 15:40:45 GMT; Path=/, SESSION=<snip> Path=/; HttpOnly', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '43653'} {"success":true,"code":"OK","msg":"Operation succeeded.",<snip>
GET https://api.kucoin.com/v1/market/open/coins 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/coins 
Response: {'Date': 'Fri, 29 Dec 2017 15:40:47 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>; Expires=Fri, 05 Jan 2018 15:40:47 GMT; Path=/, SESSION=snip; Path=/; HttpOnly', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '17325'} {"success":true,"code":"OK","msg":"Operation succeeded.<snip>
GET https://api.kucoin.com/v1/account/balance?limit=20&page=1 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514562047197', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/account/balance?limit=20&page=1 
Response: {'Date': 'Fri, 29 Dec 2017 15:40:49 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>; Expires=Fri, 05 Jan 2018 15:40:48 GMT; Path=/', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '6923'} {"success":true,"code":"OK","msg":"Operation succeeded.",<snip>
{'free': 0.0005994, 'used': 0.0, 'total': 0.0005994}
POST https://api.kucoin.com/v1/order?amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514562049758', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL
POST https://api.kucoin.com/v1/order?amount=0.0005994&price=0.04978104&symbol=ETH-BTC&type=SELL 
Response: {'Date': 'Fri, 29 Dec 2017 15:40:51 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Set-Cookie': 'AWSALB=<snip>; Expires=Fri, 05 Jan 2018 15:40:51 GMT; Path=/', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '147'} {"success":false,"code":"ERROR","msg":"The precision of amount(ETH) is incorrect. The precision of ETH is 6","timestamp":1514562051436,"data":null}

Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Test2/_test/test_kucoin.py", line 16, in <module>

    e.createLimitSellOrder('ETH/BTC', 0.00059940, 0.04978104)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1050, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 302, in create_order
    'id': self.safe_string(response['data'], 'orderOid'),
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 474, in safe_string
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] else default_value
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kroitor** [comment]
@gaardiolor, ok, both problem #1 and problem #2 should be fixed in Python as of version 1.10.513 (again, wait 5-10 minutes, then update). Tested the python case. It works now (throws an adequate exception + does not need the .truncate anymore). Let us know if it still doesn't work for you. Thx!

**Comment by gaardiolor** [comment]
ok great! I think both problems are solved.

**Comment by sportokua** [comment]
@gaardiolor 
@marcusl33 
@kroitor 
Hi, guys.
I work with Java, use api from KuCoin's websit. And I have same problem. 
I can't make POST requests with two or more parameters on Kucoin (eg. symbol=KCS-BTC&fav=1), it says that "Signature verification failed". All GET requests work fine.
Are your POST requests on Kucoin work corectly now?
I will appreciate for any information from you.

**Comment by kroitor** [comment]
@sportokua hi! Is it a new API key or did you use it earlier with any other software?

**Comment by sportokua** [comment]
@kroitor 
Yes, it is new API key. I did not use it earlier.
But I can receive my balance with GET request. So there is not problem with API key, is not it?
Also I tried use API key from another account. The result is the same.

**Comment by dmittal3** [comment]
Hi Kroitor,
I am trying to simply fetch account balances and formed below unix commands to do that:

!/Bin/Sh
kcAPIkey=5b5cxxxxxxxxx
kcSecretKey=xxxx-xxx-xxxxxxx-xxx-xxxx
nonce=$(($(date +%s%N)/1000000)) 
secret=$(echo -n "/v1/account/balances/$nonce" | base64 | openssl dgst -sha256 -hmac "$kcSecretKey" | sed 's/.*= //') 
curl -s -H "KC-API-KEY: $kcAPIkey" -H "KC-API-NONCE: $nonce" -H "KC-API-SIGNATURE: $secret" -X GET 'https://api.kucoin.com/v1/account/balances'

Error message of the file at my path: {"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1532805181671}

Can you please help as documentation doesn't seems alright and all the places I search over internet many people reporting this issue.

**Comment by dmittal3** [comment]
Hi @kroitor ,
I am trying to simply fetch account balances and formed below unix commands to do that:

!/Bin/Sh
kcAPIkey=5b5cxxxxxxxxx
kcSecretKey=xxxx-xxx-xxxxxxx-xxx-xxxx
nonce=$(($(date +%s%N)/1000000))
secret=$(echo -n "/v1/account/balances/$nonce" | base64 | openssl dgst -sha256 -hmac "$kcSecretKey" | sed 's/.*= //')
curl -s -H "KC-API-KEY: $kcAPIkey" -H "KC-API-NONCE: $nonce" -H "KC-API-SIGNATURE: $secret" -X GET 'https://api.kucoin.com/v1/account/balances'

Error message of the file at my path: {"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1532805181671}

Can you please help as documentation doesn't seems alright and all the places I search over internet many people reporting this issue.

**Comment by jaydevvaghela943** [comment]
Hello Sir,

I am new user to use CCXT on my project. I have a issue on some of functions like fetch my orders and Fills from Kucoin. When I these functions it throw error like **"AuthenticationError: KC-API-KEY not exists".**

My code is as below please provide solution....

`var kucoinData = new ccxt.kucoin({
apiKey: 'apikey',
secret: 'secret',
password:'passphrase'
});

var Data = await kucoinData.fetchMyTrades();

Please see above code and provide solution where I wrong in code....

Thanks & Regards,
Jay

**Comment by kroitor** [comment]
@jaydevvaghela943 answered your question on how to use the testnet API keys here: https://github.com/ccxt/ccxt/issues/6853#issuecomment-620726585
